### ISSUE TITLE
Add ranks in /find

### ISSUE THREAD

**Issue by MiginsMC** [Minehut/Meta#69] opened 2020-08-16 02:50 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game
**Describe the feature**

Show ranks in /find. For example, '[ADMIN] Migins is currently online [lobby 1].' Whether or not the rank and name is coloured can be decided later should this suggestion be accepted. It should also show the rank, even if they have finding disabled. Such as '[ADMIN] Migins has finding disabled.' or however it's formatted.
- This message could also be shown when you try and msg someone who has msging disabled.

**How the feature is useful**

Sometimes I just wanna see what rank someone has without /msging them or if they have it disabled. It can also be another perk for people with ranks :)
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment] 2020-08-16 02:50
This is a duplicate of #6

**Closed** 2020-08-16 02:50 UTC
Labels: duplicate, feature request
