### ISSUE TITLE
Custom Kick / Ban Screen

### ISSUE THREAD

**Issue by Sunni05** [Minehut/Meta#503] opened 2021-02-04 15:56 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Both
**Describe the feature**

I would appreciate it if we could actually have a kick / ban screen and it doesn’t kick you to the lobby, the reason for this is, unless your a laggy player like myself, you don’t actually see the message, and once your in the lobby, the /ad message comes up and the chat is cleared.
**How the feature is useful**

This feature benefits almost everyone, if your using advancedbans you can have custom kick messages, and you kinda want people to see them.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sunni05** [comment] 2021-02-04 15:57
And if that isn’t possible, at least let us have color codes in our messages :/

**Comment by Blocksnmore** [comment] 2021-02-04 15:57
Dupe of #49

**Closed** 2021-02-04 15:57 UTC
Labels: feature request
