### ISSUE TITLE
allow downloads of coreprotect databases (.db files)

### ISSUE THREAD

**Issue by jarekt** [Minehut/Meta#612] opened 2021-04-30 19:45 UTC
### Feature request

**Checklist**
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This is not a bug report, support request or plugin request
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This issue does not contain any sensitive information 

**Platform**
in-game: Java

**Describe the feature**
You should be able to download coreprotect's database files using the `/download` command similarly to how you can download worlds.

**How the feature is useful**
1. You can already download worlds and coreprotect's databases are a pretty important part of the world (= it can be useful for making local machine backups).
2. It could reduce the database's filesize as people could back it up locally and could therefore `/co purge` (= clear old database entries) without fear of losing old data from the database. This could help a lot as the databases tend to grow a lot in size over time.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jarekt** [comment] 2021-04-30 19:46
This could of course be also implemented to work from file manager in the dashboard.

**Comment by quick007** [comment] 2021-04-30 19:46
Duplicate of #11

**Comment by BluBoy3ch0** [comment] 2021-05-02 18:13
while this is nice, you could ask coreprotect themselves to add this, as it doesn't apply to 100% of people who use minehut.

https://github.com/PlayPro/CoreProtect/issues

**Comment by jarekt** [comment] 2021-05-03 10:30
> while this is nice, you could ask coreprotect themselves to add this, as it doesn't apply to 100% of people who use minehut.
> 
> https://github.com/PlayPro/CoreProtect/issues

Not really, while this doesn't apply to all minehut users it is useless for anyone except users of minehut as on normal server hosts you can just download the database over FTP (there's no FTP access to minehut except for the dashboard which doesn't allow downloads at all). I requested this, because there's already a command on minehut for downloading worlds/schematics/logs so allowing it to download coreprotect databases would not only be easy to implement but also beneficial for the reasons i listed in the main body of the issue.

**Comment by BluBoy3ch0** [comment] 2021-05-03 15:22
> Not really, while this doesn't apply to all minehut users it is useless for anyone except users of minehut (therefore there's no reason for coreprotect to implement it) as on normal server hosts you can just download the database over FTP (there's no FTP access to minehut except for the dashboard which doesn't allow downloads at all). I requested this, because there's already a command on minehut for downloading worlds/schematics/logs so allowing it to download coreprotect databases would not only be easy to implement but also beneficial for the reasons i listed in the main body of the issue.

I do think it would be nice, its not something that affects minehut as a whole which means it might not be focused on. I'm just saying that another option would be to go to the plugin itself and request the additions, which might be a more viable option than asking minehut to add it.

**Comment by jarekt** [comment] 2021-05-03 17:18
> > Not really, while this doesn't apply to all minehut users it is useless for anyone except users of minehut (therefore there's no reason for coreprotect to implement it) as on normal server hosts you can just download the database over FTP (there's no FTP access to minehut except for the dashboard which doesn't allow downloads at all). I requested this, because there's already a command on minehut for downloading worlds/schematics/logs so allowing it to download coreprotect databases would not only be easy to implement but also beneficial for the reasons i listed in the main body of the issue.
> 
> I do think it would be nice, its not something that affects minehut as a whole which means it might not be focused on. I'm just saying that another option would be to go to the plugin itself and request the additions, which might be a more viable option than asking minehut to add it.

I am sorry, but did you read anything at all of what I posted here?

**Comment by drtshock** [comment] 2021-05-12 17:28
This will be coming with custom plugins.

**Closed by drtshock** 2021-05-12 17:28 UTC
Labels: feature request, game
