### ISSUE TITLE
Server Categories/Tags

### ISSUE THREAD

**Issue by YouStoleMyHacks** [Minehut/Meta#326] opened 2020-10-19 20:11 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

 Both java and bedrock.

**Describe the feature**

Server Categories, Categories to sort minehut servers and make them more organized.
**How the feature is useful**

Add server categories, we need them. It is quite hard to find the server you are looking for with gameplay that you like. The front page is always full of unoriginal servers like skygens, skymines, prisons, skyblock, and grinders. We need a way to sort them out as it is very hard to find anything to enjoy, i would also like servers to have Tags you ca assign to them like rpg, creative, smining, prison etc. And say for example you want to find an rpg server. Just open a gui maybe above the server menu or below it. And itll say like Categories or something. You would click rpg and it would bring up any server with the tag "rpg". Overall this would really be helpful and it is also needed as original servers die out cause unoriginal servers take over minehut. It is a total mess and needs fixed, this suggestion can atleast repair a problem with unoriginality and clutter.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by YouStoleMyHacks** [comment] 2020-10-19 20:13
Oops accidentally submitted with the whole format, i ment to take some parts out. Oh well lol

**Comment by jellz** [comment] 2020-10-19 20:13
You can edit the issue

**Comment by YouStoleMyHacks** [comment] 2020-10-19 20:16
Thanks

**Comment by LukasmanMHdude** [comment] 2020-10-19 21:18
Dupe of #132 even though I told you I could integrate it in discord.

**Comment by YouStoleMyHacks** [comment] 2020-10-19 22:00
> Dupe of #132 even though I told you I could integrate it into that suggestion on discord.

Dude its my idea im not going to give someone credit if they did not help or participate with the idea. also you came up with a list not an actual response on how to implement a feature.

**Comment by Blocksnmore** [comment] 2020-10-19 22:04
> > Dupe of #132 even though I told you I could integrate it into that suggestion on discord.
> 
> Dude its my idea im not going to give someone credit if they did not help or participate with the idea. also you came up with a list not an actual response on how to implement a feature.

You can always comment on the issue and contribute, part of the checklist is " I have searched the Issue Tracker to make sure this is not a duplicate issue" and there is a dupe of what you made. Also you didn't complete the checklist.

**Comment by LukasmanMHdude** [comment] 2020-10-19 22:09
> > Dupe of #132 even though I told you I could integrate it into that suggestion on discord.
> 
> Dude its my idea im not going to give someone credit if they did not help or participate with the idea. also you came up with a list not an actual response on how to implement a feature.

You realize the goal of this is to get new features, and I would credit you on github. But its not as if the feature will say "created by Lukas#1969" or smth.

**Comment by YouStoleMyHacks** [comment] 2020-10-20 01:55
> > > Dupe of #132 even though I told you I could integrate it into that suggestion on discord.
> > 
> > 
> > Dude its my idea im not going to give someone credit if they did not help or participate with the idea. also you came up with a list not an actual response on how to implement a feature.
> 
> You can always comment on the issue and contribute, part of the checklist is " I have searched the Issue Tracker to make sure this is not a duplicate issue" and there is a dupe of what you made. Also you didn't complete the checklist.

It is not a dupe, he did not even touch the idea of it or go into anything about it. That is like saying i plagurized an essay cause i used words like the, there, why.

**Comment by LukasmanMHdude** [comment] 2020-10-20 03:29
As you like to claim that I don't add enough information, I've revised my suggestion to be more clear on all topics, especially this one where I rewrote what you made up there to be more in line with the format and include a few ideas of mine own. I also credited you.

**Comment by LukasmanMHdude** [comment] 2020-10-24 16:30
Can someone close this pls

**Comment by Sniped** [comment] 2020-10-24 17:59
As Lukas said, this was originally suggested on #132, therefore it's a duplicate. You can always comment on the relevant issue how you believe something can be revised.

**Closed by Sniped** 2020-10-24 17:59 UTC
Labels: feature request, game
