### ISSUE TITLE
server tags

### ISSUE THREAD

**Issue by umbatataae** [Minehut/Meta#665] opened 2021-06-27 12:48 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 in-game for both minecraft versions bedrock and java

**Describe the feature**
 When you click on the compass at the minehut lobby, there is a list of random servers, but what if we could choose what type server are we looking for?, they could add a "random" tag so we could go to this area that we see today with the random servers (just the normal when you click on the compass) and they could add some tags like "Sky Mine" "Gens" "PvP" "Full Skripted" and a lot more

**How the feature is useful**
Instead of just searching for a long time on the server list or just waiting for someone ad the server you want to play, just check on the tags for what you are looking for.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by DaRealMinecraftexpert** [comment] 2021-06-27 12:58
Tags already exist, but they aren't used ingame as far as I've seen

**Comment by DebitCardz** [comment] 2021-06-27 13:29
This will probably be done in some form with the new server discovery feature being talked about.

**Comment by iGalaxyYT** [comment] 2021-06-27 17:24
Duplicate of #628

**Comment by DaRealMinecraftexpert** [comment] 2021-06-28 00:26
> Duplicate of #628

Should be posted on*

**Closed** 2021-07-30 17:52 UTC
Labels: feature request
