### ISSUE TITLE
Shared networks and permissions

### ISSUE THREAD

**Issue by Giuca002** [Minehut/Meta#940] opened 2022-03-06 16:51 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Shared Dashboards for networks... All the servers on the network will be on one account and if needed maybe limit the amount of people who can share an network with credits this would help prevent people abusing the feature and still keep the needed feature.

**How the feature is useful**

When  making a network you can give permissions to other Minehut accounts so they can help make your server this could be good for devs to add plugins/skripts easily without needing to send it to the owner every time or sharing an account which could be a security threat. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by honkling** [comment] 2022-03-06 20:54
Duplicate of #13

**Closed** 2022-03-07 21:26 UTC
Labels: feature request
