### ISSUE TITLE
Increase MOTD character limit & add support for RGB text

### ISSUE THREAD

**Issue by CerialPvP** [Minehut/Meta#936] opened 2022-03-01 17:42 UTC
### Feature request

**Checklist**
- [ X ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ X ] This is not a bug report, support request or plugin request
- [ X ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ X ] This issue does not contain any sensitive information 

**Platform**

Ingame, both

**Describe the feature**

Basically, I am suggesting 2 things. Right now, Minehut has a 64 character limit on MOTD (including color codes), and you can't add RGB colors.
Yes, I know that only versions above 1.16 can see RGB colors, Minecraft already rounds up RGB colors to color codes on older versions (idk if its minecraft but whatever, it does do that)
Maybe increase the limit to 128 characters and exclude color codes so people can freely type their MOTD.
While we can use third party plugins and Skript, it still won't work.

**How the feature is useful**

First of all, it will look so good on servers, and second of all, big networks such as CubeCraft are using RGB colors.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment] 2022-03-01 17:44
dupe of #42 and #125

**Comment by BennyDoesStuff** [comment] 2022-06-30 22:33
Duplicate of #42

**Closed by BennyDoesStuff** 2022-06-30 22:33 UTC
Labels: feature request
