### ISSUE TITLE
proxy's

### ISSUE THREAD

**Issue by ninjea** [Minehut/Meta#828] opened 2021-10-20 17:38 UTC
I think with the new proxy's update we should have it so only the networks hub has to have a plan or no plan needed at all

**Comment by tarna** [comment] 2021-10-20 17:52
You just closed your previous issue and made it again and it still doesn't follow the format 🤦‍♂️

**Comment by Tringlle** [comment] 2021-10-22 03:45
Dupe of my #826

**Closed** 2022-06-28 23:19 UTC
Labels: feature request
