### ISSUE TITLE
Credit Transferring

### ISSUE THREAD

**Issue by oHeckGage** [Minehut/Meta#594] opened 2021-04-18 20:55 UTC
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Instead of other people suggesting Credit Giving/Donating, I wish for Credit Transferring. Basically, I wish that a Minehut account could transfer their credits to another account. The way I wish for this to be done is to create a Discord channel for making a request. Then, you fill out a form with you email, password, and other verification steps to ensure that there's no scamming. Then, you would make sure that the other person agrees within a certain amount of time.

**How the feature is useful**

It allows people to transfer credits from their old account to a new account. (Ex: You need a new account but you have thousands of credits on your old account. You can transfer your credits from your old account to your new one.)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by thethistle** [comment] 2021-04-18 21:17
Dupe of #377 / #517

**Closed** 2021-04-18 21:17 UTC
Labels: duplicate, feature request
