### ISSUE TITLE
Ranks in discord ?

### ISSUE THREAD

**Issue by Sunni05** [Minehut/Meta#518] opened 2021-02-13 04:51 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Discord

**Describe the feature**

My idea, some people use nicknames to display their rank status, some people use that to trick others into thinking they have the rank, what if we did rank sync? So if you got vip for example, you’d get a role in discord. Something along those lines

**How the feature is useful**

Just to obtain bragging rights 🥇 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2021-02-13 04:54
Dupe of #51

**Closed** 2021-02-13 05:17 UTC
Labels: feature request
