### ISSUE TITLE
Ranked Mute Chat

### ISSUE THREAD

**Issue by Sunni05** [Minehut/Meta#505] opened 2021-02-04 18:18 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Both
**Describe the feature**

Similar to #499, but when chat is muted, ranks can speak, not muting defaults if that makes sense. People with ranks can talk during mute chat, and ofc there’s still the /mute command if ranks are spamming, but rank spam is not common.
**How the feature is useful**

Everyone with a rank.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by killergotrekt** [comment] 2021-02-04 18:19
It still happens, there was this time where people brought spammers vip so they can spam

**Comment by Sunni05** [comment] 2021-02-04 18:20
> It still happens, there was this time where people brought spammers vip so they can spam

> ofc there’s still the /mute command.

**Comment by Sunni05** [comment] 2021-02-04 18:20
Maybe make it like legend and higher or something.

**Comment by killergotrekt** [comment] 2021-02-04 18:21
you're assuming ranked players don't break the rules 
> ofc there’s still the /mute command.

umm no the rules are applied to everyone equally

**Comment by LukasmanMHdude** [comment] 2021-02-04 18:22
Lets not make chatting p2w pls. Also, why would you include the issue you made a dupe of in the post, showing you already know about it. Pls close this

**Closed** 2021-02-04 18:25 UTC
Labels: feature request
