### ISSUE TITLE
Team Members

### ISSUE THREAD

**Issue by ikeyIX** [Minehut/Meta#710] opened 2021-08-05 19:34 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Both

**Describe the feature**
 I am suggesting a Team Members ability to the Minehut Dashboard. You can add peoples emails to the minehut and apply what stage of management they have. For example you could add 'totallyrealemail@gmail.com' to have the management rank 'Owner'.

**How the feature is useful**
 It's way better than giving random players your console and more to risk them backstabbing you or resetting your server.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2021-08-05 19:36
Dupe of #13

**Comment by Randoms-Squad** [comment] 2021-08-06 22:43
that is a good idea

**Comment by Tringlle** [comment] 2021-08-13 02:00
Dupe of #13 (Close this)

**Comment by BennyDoesStuff** [comment] 2022-06-28 23:17
Duplicate of #13

**Closed by BennyDoesStuff** 2022-06-28 23:17 UTC
Labels: feature request
