### ISSUE TITLE
Centre checkout text,

### ISSUE THREAD

**Issue by aroze123** [Minehut/Meta#322] opened 2020-10-17 20:44 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
The credit checkout text isn't centred. Centre it,
![image](https://user-images.githubusercontent.com/68871455/96353132-422e5f80-10c1-11eb-9697-c4b322fa31c9.png)

**How the feature is useful**
Just annoying to look at and it's an easy fix,

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment] 2020-10-17 22:10
I can't find the issue rn, but pretty sure this is a dupe of one someone made a bit ago. regardless, that's on PayPal's end not theirs.

**Comment by Sniped** [comment] 2020-10-17 22:30
Yeah, I'm pretty sure the constraints for how developers can customize the checkout button lie in this [documentation](https://developer.paypal.com/docs/archive/checkout/how-to/customize-button/).

**Comment by Double0negative** [comment] 2020-10-18 07:22
This is paypals button, not ours, we dont control what it looks like

**Closed by Double0negative** 2020-10-18 07:22 UTC
Labels: feature request, web (core)
