### ISSUE TITLE
Changing Console Email 

### ISSUE THREAD

**Issue by Shlba** [Minehut/Meta#642] opened 2021-06-05 07:53 UTC
**Platform**
Website

**Describe the feature**
Add a way to change the email which is associated with the Console account. 

**How it would work**
• user clicks an option to change their console Email
• Sends an Email to you, telling them to check their email
• user changes settings from a link sent to their email

**How the feature is useful**
Some users may need to change their console email due to a variety of reasons:
• Used a wrong email to begin with, wants to change it.
• Wants to share a console account, but not personal information.
• Email contains personal information.
• Email is not secure, they do not have permanent access to it.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment] 2021-06-05 12:29
Duplicate of #265

**Closed** 2021-06-05 13:09 UTC
Labels: feature request
