### ISSUE TITLE
Bungeecord Player servers

### ISSUE THREAD

**Issue by XePup** [Minehut/Meta#539] opened 2021-02-27 04:16 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Add the possibility for player servers to be linked to create a bungeecord environment to make network

**How the feature is useful**

It will allow people to make bungeecord player networks so then we can create networks without leaving the minehut community, It will also free up a lot of names.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment] 2021-02-27 04:18
dupe of #119 and #484

**Closed** 2021-02-27 13:44 UTC
Labels: duplicate, feature request
