### ISSUE TITLE
Dashboard quality of life changes 

### ISSUE THREAD

**Issue by DereC4** [Minehut/Meta#498] opened 2021-01-29 18:06 UTC
### Feature request

**Checklist**
- [Y ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [Y ] This is not a bug report, support request or plugin request
- [Y ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [Y ] This issue does not contain any sensitive information 

**Platform**
Java

**Describe the feature**
Attempting to bookmark any server pages will just make those redirect to the dashboard. Likewise, when refreshing while browsing server tabs (for example, the "settings" tab) will send you back to the main dashboard. If the site could allow you to save individual spots on the server (such as https://minehut.com/dashboard/files) and allow you to directly go to those via a link instead of being sent to the dashboard every time and having to navigate to that specific tab every time. 

**How the feature is useful**

It benefits a lot of people as we can directly jump to server sites without having to start from the dashboard; just a quality of life thing. Say you want to go directly to your permissions folder and edit that but instead get sent back to the dashboard and have to navigate to there all over again. This could fix that problem. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment] 2021-01-29 18:38
dashboard needs a full revamp/recode

**Comment by LukasmanMHdude** [comment] 2021-01-29 18:40
also dupe of #378

**Comment by killergotrekt** [comment] 2021-01-29 18:45
> dashboard needs a full revamp/recode

create a new issue

**Closed** 2021-01-29 21:39 UTC
Labels: duplicate, feature request, web (core)
