### ISSUE TITLE
AutoOP Server Owner

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#586] opened 2021-04-11 01:43 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

**Describe the feature**

I think the console should auto-op the server owner if their Mc account is linked to their minehut account.
**How the feature is useful**

It benefits those people who don’t know / are new to minehut.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by quick007YT** [comment] 2021-04-11 01:44
most people that are new probably won't have their acc linked. Would be cool if when creating a new server a promt would come up to type ur mc username to op it

**Comment by MiginsMC** [comment] 2021-04-11 02:01
Dupe of #448

**Closed by MiginsMC** 2021-04-11 02:01 UTC
Labels: feature request
