### ISSUE TITLE
Allow exp grouping to be disabled, or allow edits to spigot.yml

### ISSUE THREAD

**Issue by D-e-r-e-k-M** [Minehut/Meta#279] opened 2020-09-22 01:54 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java edition 

**Describe the feature**

Remove EXP grouping from spigot.yml or allow edits to the `
world-settings:
  default:
    merge-radius:
      exp: -1`
exp line in spigot.yml

**How the feature is useful**

This feature is useful for xp farms such as gold farms, and enderman farms as it allows xp to act naturally similar to how vanilla Minecraft works. Without being able to edit this line xp farms are useless in most cases which can also make the mending enchant usless
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2020-09-22 01:54
Dupe of #8

**Comment by LukasmanMHdude** [comment] 2020-09-22 07:53
Why add duplicate instead of closing it lol

**Closed** 2020-09-23 23:22 UTC
Labels: duplicate, feature request
