### ISSUE TITLE
Bedrock direct server IP

### ISSUE THREAD

**Issue by Reimagining** [Minehut/Meta#784] opened 2021-09-07 21:38 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Bedrock
**Describe the feature**

Rather than bedrock.minehut.com --> /join servername, Minehut should add a direct server IP like they already do for Java. servername.minehut.gg is the current direct IP for java and bedrock could be servername.minehutbedrock.gg or something
**How the feature is useful**

Pretty self-explanatory, direct IPs are more convenient and better for owners and players that want to join their server. Especially when advertising.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment] 2021-09-07 21:55
dupe of #716

**Comment by Reimagining** [comment] 2021-09-07 23:50
mb. I searched almost every term but not "feature for bedrock".

**Comment by BennyDoesStuff** [comment] 2021-09-10 19:36
Duplicate of #716

**Closed by BennyDoesStuff** 2021-09-10 19:36 UTC
Labels: feature request
