### ISSUE TITLE
I’d like to go even further into the “Credit Giving” feature

### ISSUE THREAD

**Issue by Kastor07** [Minehut/Meta#866] opened 2021-11-24 00:25 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

Credit Gifting through the dashboard.
**How the feature is useful**

Please read the whole thing. Other people when suggesting features like this fail to make measures around the whole "alt + vote = infinite credits" thing, but I have found one. Instead of making it to where the user can donate already existing credits, make it to where when they would go to donate credits, they would have to buy new credits and those would be given to the user. How I imagine it would work is; Click a button called "Donate Credits" or something along those lines in the credit buying menu, you can choose the amount you wish to buy (like in the current credit menu), you enter the persons IGN and if their MC account is linked to their dashboard, you allow the user to buy the credits for the other user.
All though some people may not like this, as you have to buy new credits, there is no other way to prevent infinite vote credits besides logging how many credits of the user are from voting or not, and preventing those free credits from getting donated.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by erenkarakal** [comment] 2021-11-24 05:45
so you want to make it so you can buy credits for someone else? thats great

**Comment by BennyDoesStuff** [comment] 2021-11-29 20:13
Duplicate of #377

**Closed by BennyDoesStuff** 2021-11-29 20:13 UTC
Labels: feature request
