### ISSUE TITLE
Transfer Players

### ISSUE THREAD

**Issue by MrEnxo** [Minehut/Meta#325] opened 2020-10-19 02:42 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Java and Bedrock

**Describe the feature**
Be able to transfer players to different servers owned by the account the server is on. This could be done with a skript addon or a plugin you install which has a custom command only executable by ops and console

**How the feature is useful**
This benefits everyone even minehut there is now reasons to buy different servers on your account and there can now be networks which means you can have multiple gamemodes on one server and it will run well

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2020-10-19 02:48
Basicly a dupe of #119

**Comment by LukasmanMHdude** [comment] 2020-10-19 02:50
Pretty sure there's also been some talk about adding some skript hooks maybe for paid servers. Still a dupe of ^

**Comment by RichieNy** [comment] 2020-10-19 18:12
Duplicate Issue

**Closed by RichieNy** 2020-10-19 18:12 UTC
Labels: duplicate
