### ISSUE TITLE
Allow the deletion of servers

### ISSUE THREAD

**Issue by CymaMC** [Minehut/Meta#794] opened 2021-09-19 10:15 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game and Website

**Describe the feature**

Being about to fully delete a server instead of just being able to reset it.

**How the feature is useful**

A lot of people want a way to delete a server instead of resetting it. Adding the option to delete servers will also allow Minehut to clear a little bit of storage space (not really that beneficial but still a little nice I guess..)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoolProgrammerX** [comment] 2021-09-20 03:21
Duplicate of #521.

**Comment by BennyDoesStuff** [comment] 2021-09-21 18:05
Duplicate of #521

**Closed by BennyDoesStuff** 2021-09-21 18:05 UTC
Labels: feature request
