### ISSUE TITLE
saving time

### ISSUE THREAD

**Issue by Extrample** [Minehut/Meta#878] opened 2021-12-03 17:50 UTC
### Feature request

**Checklist**
- [ ya ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [  feature request ] This is not a bug report, support request or plugin request
- [ ya ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ idk ] This issue does not contain any sensitive information 

**Platform**

like the old plugins tab you can install plugins without the server restarting, but now if you wanted to install something it already restarts, I know that there's this thing that you can just do install but not restart but it's still annoying that you have to install them to the server on every plugin, so maybe like a button that you can install all of your plugins that are owned or maybe like they autoinstall or install multiple plugins but specific ones, so its easier for people who make a new server or reset their server to save their time (sorry its too long)

**How the feature is useful**

saves time

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by ntrogen** [comment] 2021-12-12 20:16
There's already many issues like this however I absolutely agree with you and hate the addon panel

**Comment by CoreyShupe** [comment] 2022-02-09 21:38
Dupe of #849

**Closed by CoreyShupe** 2022-02-09 21:38 UTC
Labels: feature request
