### ISSUE TITLE
Email changes 

### ISSUE THREAD

**Issue by Giuca002** [Minehut/Meta#701] opened 2021-07-31 19:50 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

A button to change our email

**How the feature is useful**

For our privacy
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment] 2021-07-31 19:51
dupe of #265

**Comment by Giuca002** [comment] 2021-08-01 13:15
they are all closed 

> dupe of #265

**Comment by PundaChen** [comment] 2021-08-01 13:50
265 is still open

**Closed** 2021-08-01 13:51 UTC
Labels: feature request
