### ISSUE TITLE
paper.yml file should be able to be edited

### ISSUE THREAD

**Issue by ManosSef** [Minehut/Meta#241] opened 2020-09-01 14:55 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

I believe the paper.yml file should be able to be edited because there is so much to customize in it. Well, there may be some settings that change some vital options for the server that shouldn't be edited (things with the server port and such), but this could be fixed by making a GUI like that of the server.properties file, that only changes world settings and in-game settings in general.

**How the feature is useful**

I believe this feature would add more customization to Minehut servers that may be found in other server hosts.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by WallyTube** [comment] 2020-09-01 15:00
Duplicate of #5

**Comment by iGalaxyYT** [comment] 2020-09-01 15:44
> Duplicate of #5

This is a duplicate of #8, not #5

**Comment by WallyTube** [comment] 2020-09-01 15:59
> This is a duplicate of #8, not #5

Yeh, but it should go into the same batch

**Comment by BennyDoesTheStuff** [comment] 2020-09-01 16:18
Duplicate, closing.

**Closed by BennyDoesTheStuff** 2020-09-01 16:18 UTC
Labels: feature request
