### ISSUE TITLE
Enable spigot.yml editing.

### ISSUE THREAD

**Issue by xenitrogen** [Minehut/Meta#556] opened 2021-03-18 12:55 UTC
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**
Java

**Describe the feature**
Enable spigot.yml again, it got disabled randomly & This means server owners wont be able to edit the "You are not whitelisted on this server!" message.

**How the feature is useful**
When you run an event server you'd rather instead of "You are not whitelisted." you can say "There's no events running! Please join our discord for the next event, https://discord.gg/minehut"

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2021-03-18 14:49
dupe of #444

**Closed** 2021-03-18 15:42 UTC
Labels: duplicate, feature request, game
