### ISSUE TITLE
Recently Visited Page

### ISSUE THREAD

**Issue by OriginallySmokey** [Minehut/Meta#795] opened 2021-09-20 17:09 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game

**Describe the feature**

It would be cool if the main menu where all the servers are if you had a "Recently Visited" page to see recent servers you joined.

**How the feature is useful**

This feature would allow players who forgot a servers name/IP that they joined and enjoyed to revisit. This has happened to me multiple times where I wanted to revisit a server I joined but I forgot the name and could never rejoin.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment] 2021-09-21 16:43
dupe of #337

**Comment by BennyDoesStuff** [comment] 2021-09-21 18:05
Duplicate of #337

**Closed by BennyDoesStuff** 2021-09-21 18:05 UTC
Labels: feature request
