### ISSUE TITLE
FIX LAG

### ISSUE THREAD

**Issue by ksu-tech** [Minehut/Meta#496] opened 2021-01-27 18:54 UTC
Minehut, while playing on a server made with your hosts, I experience a lag spike every 30-45 minutes. It makes the server very hard and very unplayable when I try playing long amounts of time with my friends

**Comment by PundaChen** [comment] 2021-01-27 19:10
First of all, please follow the format that was given to you when you create an issue.
Second of all, the dev team is doing their best to fix this, a small lag spike every hour is nothing, I don't see how this makes your server unplayable, we've gone from all users haveing 3k ping to barely having any lag. It's also very likely that this lag is caused by you playing for long amounts of time with multiple users, this can cause lag, another thing that can cause lag is having a ton of plugins or having very little RAM.

**Comment by Sniped** [comment] 2021-01-27 19:21
As @PundaChen, please follow the format in the future when making issues; not only that, this is a dupe of #460 for the most part. If you deduce that Minehut is the sole reason you're getting lag and none of the things that Panda has mentioned, I would recommend commenting on #460 further details about your server so admins can take a look. I would first, however, look into what Panda has mentioned as those are common things that can cause lag on your server.

**Closed by Sniped** 2021-01-27 19:21 UTC
Labels: feature request

**Comment by LukasmanMHdude** [comment] 2021-01-27 19:22
> As @PundaChen, please follow the format in the future when making issues; not only that, this is a dupe of #460 for the most part. If you deduce that Minehut is the sole reason you're getting lag and none of the things that Panda has mentioned, I would recommend commenting on #460 further details about your server so admins can take a look. I would first, however, look into what Panda has mentioned as those are common things that can cause lag on your server.

why are you referencing a closed issue?
