### ISSUE TITLE
Minehut Forums Bug

### ISSUE THREAD

**Issue by M1nordragonMC** [Minehut/Meta#615] opened 2021-05-02 21:40 UTC
![Screenshot (92)](https://user-images.githubusercontent.com/81280361/116828547-5ae9f880-ab6d-11eb-9cd0-336b3e7d5fb0.png)
It has been showing this screen for the past 20 mins.

**Comment by Blocksnmore** [comment] 2021-05-02 21:40
Unable to reproduce, try clearing your cache ![https://blocksnmore.is-inside.me/M7CCbUi5.png]
Also follow the format smh.

**Comment by Sniped** [comment] 2021-05-02 21:51
This issue completely ignores the format and has a vague title. Please use the included format when creating a bug report and I encourage you to make your title more specific to the bug you're reporting. I'm going to give you a day to do this, otherwise I'll be closing this issue.

**Comment by Blocksnmore** [comment] 2021-05-08 16:43
@Sniped you should probably close this

**Comment by Sniped** [comment] 2021-05-08 21:53
> @Sniped you should probably close this

Forgot about this, closing now due to failure to follow the format.

**Closed by Sniped** 2021-05-08 21:53 UTC
Labels: bug, invalid, web (forum)
