### ISSUE TITLE
Server linking

### ISSUE THREAD

**Issue by Reimagine-Matias** [Minehut/Meta#571] opened 2021-03-29 13:38 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website, In-game (Both Versions)
**Describe the feature**

Adding a way to link servers. I am aware you removed /server function but I'm not sure if you are ever bringing this back. I would suggest a way to link servers within the web panel maybe for a charge. This would be equivalent to having /server back but more regulated. If a server is linked there should be a command to allow to join to our linked server. Again, this would be better with /server but I'm not too sure if that is ever coming back or its reasons.
**How the feature is useful**

Many big and small servers would love this option, prominently network type servers. I know I and many have wanted this feature since it was removed and its no surprise that the linking servers YouTube guide is still being watched until now in the minehut tutorials channel.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by quick007YT** [comment] 2021-03-29 17:04
semi dupe of #484

**Comment by quick007YT** [comment] 2021-03-29 17:04
actual dupe of #119

**Comment by Sniped** [comment] 2021-03-30 14:55
**/server** is planned to come back completely, as seen in the issue @quick007YT mentioned, therefore a more regulated equivalent of the command isn't needed.

**Closed by Sniped** 2021-03-30 14:55 UTC
Labels: feature request
