### ISSUE TITLE
Not counting specific plugins to the pl limit

### ISSUE THREAD

**Issue by Blocksnmore** [Minehut/Meta#308] opened 2020-10-11 19:11 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Server
**Describe the feature**

Plugins like via* and Protocolsupport shouldn’t count to the plugin limit
**How the feature is useful**

Theres a lot of servers running MH10 and the main issue with all of them is they only support the server version due to the pl limit this is kinda a repost of https://discordapp.com/channels/546414872196415501/744075635114115142/764926912052854815 except that its not required like that suggestion said
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment] 2020-10-11 19:15
Already been confirmed by trent that this won't happen I believe

**Comment by LukasmanMHdude** [comment] 2020-10-12 01:05
I personally think that via version should be toggleable through the panel and allows you to set select allowed versions. Protocol support isn't that good of a plugin compared to via (can't see players sometimes, no good block sawing between versions, and just more bugs overall)

**Comment by Sniped** [comment] 2020-10-14 20:02
This is a duplicate of #180 it seems like, where Benny has stated that we don't want to exclude specific plugins from the plugin limit.

**Closed by Sniped** 2020-10-14 20:02 UTC
Labels: duplicate, feature request, web (core)
