### ISSUE TITLE
Alias For /friend

### ISSUE THREAD

**Issue by ballxishot** [Minehut/Meta#438] opened 2020-12-17 04:43 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game and Both

**Describe the feature**

An alias for /friends so it can be easier, for example /f add BallxIsHot or /f list

**How the feature is useful**

It would make it quicker and easier for players to type these commands.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by ballxishot** [comment] 2020-12-17 04:45
It is connected to Migin's suggestion but with all of the /friend commands.

**Comment by Blocksnmore** [comment] 2020-12-17 04:46
This was confirmed by staff iirc that it won’t happen as they don’t want to take up commands that server owners can use

**Comment by Sniped** [comment] 2020-12-17 06:11
If it's connected to issue #193, does that mean that you're suggesting only the lobbies to include these aliases?

**Comment by ballxishot** [comment] 2020-12-18 05:13
> If it's connected to issue #193, does that mean that you're suggesting only the lobbies to include these aliases?

Yes, only lobbies since I realised that it would clash with other commands.

**Comment by LukasmanMHdude** [comment] 2020-12-18 19:56
imo it would be better to give feedback on another suggestion then just making a new one

**Comment by Sniped** [comment] 2020-12-18 20:43
> imo it would be better to give feedback on another suggestion then just making a new one

Yeah, #193 should've just been given feedback instead of making an entirely new issue for it, so I'm going to close this one as a dupe.

**Closed by Sniped** 2020-12-18 20:43 UTC
Labels: feature request, game
