### ISSUE TITLE
Joining Whitelisted Servers

### ISSUE THREAD

**Issue by Sourblock** [Minehut/Meta#310] opened 2020-10-13 12:46 UTC
#284 # Feature request

**Checklist**
- [yes ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [yes ] This is not a bug report, support request or plugin request
- [yes ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [yes ] This issue does not contain any sensitive information 

**Platform**
java

**Describe the feature**
 80% of the time when you join a server at random you get the whitelisted message. It get's *very* annoying. you should also do the same with empty servers

**How the feature is useful**
people can actually join servers that aren't whitelisted or empty

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment] 2020-10-13 12:47
What exactly is the suggestion here? All you said is that you can't join most of the servers ;;

**Comment by Sourblock** [comment] 2020-10-13 12:48
So when joining a random server you don't get "This server is whitelisted" message because most servers you join are. Also, when you do join, its usually an empty server with no players. They should have a detection system for if its whitelisted/no players

**Comment by PundaChen** [comment] 2020-10-13 12:50
So what happens when you try joining a whitelisted server if whatever idea you have was implemented? I'm kinda confused here

**Comment by Sourblock** [comment] 2020-10-13 13:08
It just doesn't send you to servers that are whitelisted. If the server is whitelisted, it tries to send you to a different one, until it finds one that isnt

**Comment by PundaChen** [comment] 2020-10-13 13:10
Okay okay so lemme get this straight, so if I want to join X server but it's whitelisted it'll instead just send me to another server without me wanting to go to that server nor telling me that it's whitelisted?

**Comment by PundaChen** [comment] 2020-10-13 13:34
Then this is a copy of #10 which is already planned, please close >.>

**Comment by Double0negative** [comment] 2020-10-13 18:12
Closing as dupe of #10

**Closed by Double0negative** 2020-10-13 18:12 UTC
Labels: duplicate, feature request
