### ISSUE TITLE
Make the Via Plugins all add up to 1 plugin slot.

### ISSUE THREAD

**Issue by WallyTube** [Minehut/Meta#180] opened 2020-08-16 15:39 UTC
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website / Java

**Describe the feature**
Yes, I know this is a controversial topic, but let's do the math here. ProtocolSupport does the exact same things as the via plugins, and takes up one third of the amount of necessary plugins slots. I like to switch back and forth between Protocol and Via based on the current state of bugs one plugin has. It just doesn't make sense for me to have to sacrifice 2 extra plugin slots because of bugs.

**How the feature is useful**
Prevents players from paying to fix bugs?

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by recalibrated** [comment] 2020-08-16 17:01
Duplicate of #66

**Comment by WallyTube** [comment] 2020-08-16 17:39
> Duplicate of #66

farwl has 0/4 tasks complete <3

**Comment by recalibrated** [comment] 2020-08-16 17:57
Does that not make it a dupe? It's the same suggestion/request.

**Comment by BennyDoesTheStuff** [comment] 2020-08-23 21:09
This is a duplicate, and additionally we’ve already mentioned in the past that this will not be happening. If we do it with Via, then it becomes a whole issue on whether we should do it with x plugin and so on.

**Closed by BennyDoesTheStuff** 2020-08-23 21:09 UTC
Labels: feature request, web (core)
