### ISSUE TITLE
increase entity-tracing-range in spigot.yml on your servers a bit now it does not go ferther than like 40 blocks i can not see any other players in the erver unless thay are verry close to me.

### ISSUE THREAD

**Issue by lostZwolf** [Minehut/Meta#540] opened 2021-02-27 15:24 UTC
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

**Describe the feature**

**How the feature is useful**

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2021-02-27 16:01
Dupe of #444

**Comment by Sniped** [comment] 2021-02-28 20:50
Please follow the format in the future as well, fields **Platform**, **Describe the feature**, and **How the feature is useful** should all be filled out.

**Closed by Sniped** 2021-02-28 20:50 UTC
Labels: feature request
