### ISSUE TITLE
Plugin versions

### ISSUE THREAD

**Issue by Blocksnmore** [Minehut/Meta#173] opened 2020-08-16 15:14 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

This feature mainly extends #20 but if that does happen add a selector for what version of a plugin you can add, since some plugins might need an older version to run on diffrent server versions
**How the feature is useful**

Make more plugins work when #20 is implemented 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by recalibrated** [comment] 2020-08-16 17:04
Duplicate of #20, could've just commented under it per " Feel free to discuss the idea in the comments."

**Comment by jellz** [comment] 2020-08-17 07:17
Hey, if you want to add onto another issue please use the issue's comments section :)

**Closed by jellz** 2020-08-17 07:17 UTC
Labels: feature request
