### ISSUE TITLE
Add in AIRPLANE!! ( I think im in the right area. now if not delete dis then )

### ISSUE THREAD

**Issue by SkeppysPenguin** [Minehut/Meta#747] opened 2021-08-20 15:50 UTC
**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

Platform
Website

Describe the feature
Airplane is a server software fork of paper. it is more optimized and stable for servers running 1.16 and 1.17 servers. And has no lag to it, It also makes the server start up a lot faster.

How the feature is useful
It is useful to people who run 1.16 and 1.17 servers, it optimizes the server so it runs smoother, with no lag, no matter on what the server type is. the TPS is always 20. and its free to download. at: https://airplane.gg/
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Tringlle** [comment] 2021-08-20 15:57
Do not make duplicate posts.

**Comment by BennyDoesStuff** [comment] 2021-08-20 16:06
Duplicate of #722

**Closed by BennyDoesStuff** 2021-08-20 16:06 UTC
Labels: feature request
