### ISSUE TITLE
I’d like to revisit the “Credit Giving” feature.

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#517] opened 2021-02-13 04:21 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Web
**Describe the feature**

Alright, I have read some of the other credit donation things. I want to bring up a new perspective. What if players can only give other players credits, if the accounts were NOT registered on the same IP / and the person on the other end has to accept the credits within a certain amount of time, and when they do they have to verify their email. This would be helpful if they had to accept on the other end because you can’t have 2 accounts open at the same time on one device.

**Now, I am aware this is still very similar, but I’m just adding security so they can’t transfer very easily, but at the same time, you can get other people to vote in your name and it still goes through, don’t say this is wrong because I’ve been using it for over a month. There will always be ways through all security.**

**How the feature is useful**

This benefits nearly everyone.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2021-02-13 04:28
The diffrent ip etc can eaisly be bypassed using vpns and alts

**Comment by Sunni05** [comment] 2021-02-13 04:31
> There will always be ways through all security.

**Comment by Sniped** [comment] 2021-02-13 05:13
While there may always be ways to bypass security measures, to have a security measure in place that can be done as easily as just going on your phone and turning on data doesn't make any sense to me, it could also even be bypassed through just going on another computer.

**Comment by Sunni05** [comment] 2021-02-14 20:12
> While there may always be ways to bypass security measures, to have a security measure in place that can be done as easily as just going on your phone and turning on data doesn't make any sense to me, it could also even be bypassed through just going on another computer.
> 
> Personally, I like #377's way of implementing a credit donation system rather than giving credits, you would be able to buy credits except the credits would just go to the person you're buying them for.

Yes, I do like that feature too, but sometimes it’s just easier to give credits to players.

**Comment by LukasmanMHdude** [comment] 2021-02-20 15:49
Would allow people to abuse voting more than they already do, no.

**Comment by awaffle1** [comment] 2021-02-20 17:54
> Would allow people to abuse voting more than they already do, no.

What do you mean by that...?

**Comment by LukasmanMHdude** [comment] 2021-02-20 21:58
get multiple accounts -> vote on them -> get credits -> send all the credits to one account

**Comment by Sunni05** [comment] 2021-02-20 22:04
> get multiple accounts -> vote on them -> get credits -> send all the credits to one account

Top.gg tries their best to prevent alts, you can’t vote if someone on your network already has.

**Comment by Blocksnmore** [comment] 2021-02-20 22:33
> > get multiple accounts -> vote on them -> get credits -> send all the credits to one account
> 
> Top.gg tries their best to prevent alts, you can’t vote if someone on your network already has.

3 letters: VPN

**Comment by Sunni05** [comment] 2021-02-20 23:15
> > > get multiple accounts -> vote on them -> get credits -> send all the credits to one account
> > 
> > 
> > Top.gg tries their best to prevent alts, you can’t vote if someone on your network already has.
> 
> 3 letters: VPN

Oh, trust me, I’ve tried...

**Comment by Tringlle** [comment] 2021-05-24 17:29
I’m going to lock this due to inactivity.

**Comment by quick007** [comment] 2021-05-24 18:35
uhhhhhh

**Comment by TrueReassembly** [comment] 2021-11-05 22:25
A credit donation system would be a gold mine for people who hack accounts. The ability to buy them as a gift is better

**Comment by BennyDoesStuff** [comment] 2021-11-29 20:12
Duplicate of #377

**Closed by BennyDoesStuff** 2021-11-29 20:12 UTC
Labels: feature request, web (core)
