### ISSUE TITLE
Allows the editing of the 'try =' feature in Velocity

### ISSUE THREAD

**Issue by FullyDeactivated** [Minehut/Meta#901] opened 2022-01-07 02:16 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website / Velocity

**Describe the feature**
Currently Minehut does not allow you to modify the `try = ["SERVER1", "SERVER2"]` inside of the Velocity Config which Minehut automatically sets to contain every server so I believe we should be allowed to modify this part of the config as it could cause some issues if you are doing certain things.

**How the feature is useful**
The `try = ["SERVER1", "SERVER2"]` is Velocitys fallback system which is not made for having every server listed on there and only really made for having your Lobby servers on there so currently with every server listed on there if you get kicked from SERVER1 for whatever reason you get sent to SERVER2 and vice versa which could cause issues.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by ReportCardsMC** [comment] 2022-01-07 22:20
One way to kinda work around this would be using a redis server to track where you send players to so that when a player starts to connect to a non-lobby server, you check the redis to see if that's the correct server, and if not you can kick them from the network

**Comment by BennyDoesStuff** [comment] 2022-06-30 22:24
Duplicate of #858

**Closed by BennyDoesStuff** 2022-06-30 22:24 UTC
Labels: feature request
