### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#758] opened 2021-08-23 18:38 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

A "Delete Server" button on the Danger Zone page
**How the feature is useful**

It benefits people who like to use the Creation Wizard, and people who don't want their minehut panel cluttered with useless servers.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment] 2021-08-23 18:40
dupe of #521

**Closed** 2021-08-23 21:58 UTC
Labels: feature request
