### ISSUE TITLE
Increasing storage limit.

### ISSUE THREAD

**Issue by TheEpicFaceGamer** [Minehut/Meta#588] opened 2021-04-14 01:31 UTC
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

Hey, please increase the storage limit as a payable option. Our server has been crashing non stop and i've had to contact super league 3 times in a span of a week. So many people would find this issue as people are having people go far out on smps and would help people alot.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BurningBrimstone** [comment] 2021-04-14 01:50
Dupe of #582

**Closed** 2021-04-14 01:54 UTC
Labels: feature request
