### ISSUE TITLE
Voting system for player servers

### ISSUE THREAD

**Issue by RedStorm1024** [Minehut/Meta#372] opened 2020-11-10 14:21 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
In-game, for both java and bedrock

**Describe the feature**
A way to rate the player servers with for example a 1 to 5 note or thumbs up and thumbs down.
With this there could be a way to rank servers by their note instead of their player count

**How the feature is useful**
This would allow people to have a clear and easy way of knowing if a server is good, since players count is not a good indicator.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment] 2020-11-10 14:58
This suggestion is a duplicate of https://github.com/Minehut/Meta/issues/352, if you have any suggestions for how it can be improved, please reply to that ticket instead of creating a similar ticket.

Closed as dupe of https://github.com/Minehut/Meta/issues/352

**Closed by Sniped** 2020-11-10 14:58 UTC
Labels: feature request
