### ISSUE TITLE
Serverlists and Bumping

### ISSUE THREAD

**Issue by ikeyIX** [Minehut/Meta#726] opened 2021-08-13 16:05 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
My feature is a Server List page for the Minehut website instead of the list for all the servers Minehut has at the moment. The list would have all the servers that are registered on Minehut (even if they are offline) on the list in ranks. To rank up the server you can use a new feature I am suggesting called 'Bumping'. 

In game you can do a command /bump <server> and it would add 1 vote to the server on the server list. Doing that it would rank up the server and make the server stand out more against all the offline free servers. BUT bumping will be only available once a day per IP adress so there is no spamming bumps.

As well as server bumping and a server list there would also be a feature where you can advertise your Minehut server on the server list. Doing a advertisement on the server list would be similar to the other popular server lists, it would have your banner on the top of the screen and have your ip as well but this would be different. You can buy a advertisement on the server list out of Minehut credits (I would say roughly 1.5 - 5k credits for a week).

While on the Minehut server list you could also click on a server. Instead of it only showing your ip you can customize that to now show a custom banner, description, tags, logo and a discord server. As well as all them there would also be statistics about your server's Weekly Players, Times Advertised in the /hub, Times Bumped, Top Advertiser, Plugins and lots more.

I also think if this all comes true Minehut releases almost a Votifier type thing to their server list so if a player bumps their server they will get a reward, but that is just what I think would be cool and lots of the community wanted Votifier on their servers so its close enough.

**How the feature is useful**
This new feature can help your server stand out against all the free and offline servers that no one uses. It can make your server look better and have a better description that showcases how to play your server. You can also use this to help your player base so you wont have little to 0 players online just because no one can see your /ad in the hub chat.

I hope my Minehut feature request is accepted as I have spent ages thinking about what Minehut can do to make their players have a better way to advertise their server other than on /ad in hub chat.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by DaRealMinecraftexpert** [comment] 2021-08-13 17:22
The Bumping part was already suggested in #352

**Comment by BennyDoesStuff** [comment] 2021-09-07 21:47
Duplicate of #352

**Closed by BennyDoesStuff** 2021-09-07 21:47 UTC
Labels: feature request
