### ISSUE TITLE
Join messages 

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#316] opened 2020-10-15 19:40 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Ingame, lobby

**Describe the feature**
Ability to turn off join messages in the lobby and perhaps ability to make it not send the message when you join the lobby

**How the feature is useful**
Join messages tend to spam the lobby, being able to turn off your own join messages would be nice for people that don't want to be noticed (for example if a staff wants to join a lobby to view an inappropriate skin or something)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Double0negative** [comment] 2020-10-15 20:02
Join messages are so limited, both to the specific lobby and to specific roles that I really wouldn't consider it spam (Ive been sitting in the lobby for 10 minutes and haven't seen a single join message). Being able to turn your own messages off is something that could be useful though.

**Comment by PundaChen** [comment] 2020-10-15 20:04
I mean quite often I've have 10 people join in a short time, if servers crash it's annoying too and if someone's account is bugged so it sends spam join messages which happen very often >.>

**Comment by SilentF1ame** [comment] 2020-10-15 20:08
I agree that is could be nice being able to turn off your own join messages because sometimes you might not want to be noticed (especially youtubers and staff) for example.

**Comment by jellz** [comment] 2020-10-15 20:14
There used to be a setting for Join Message Visibility, the options were Staff, Donors, All and None IIRC

**Comment by Double0negative** [comment] 2020-10-15 20:16
Well the bugged join messages (default messages) are because of errors on our end not properly canceling join messages in the first place, so having a overall disable wouldn't fix that. However that is a bug that needs to be looked into and fixed.

**Comment by LukasmanMHdude** [comment] 2020-10-15 20:21
> Well the bugged join messages (default messages) are because of errors on our end not properly canceling join messages in the first place, so having a overall disable wouldn't fix that. However that is a bug that needs to be looked into and fixed.

would to be helpful to make a dedi bug for that or no?

**Comment by Double0negative** [comment] 2020-10-15 20:26
Sure

**Comment by BennyDoesStuff** [comment] 2022-06-30 20:06
Duplicate of #137

**Closed by BennyDoesStuff** 2022-06-30 20:06 UTC
Labels: feature request, game
