### ISSUE TITLE
File Manager tab multiple lines

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#93] opened 2020-08-16 03:20 UTC
### Feature request

**Platform**
 Website (File Manager text editor)

**Describe the feature**

Make it so when you highlight multiple lines and hit tab, it tabs all of them, not just one..

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by iGalaxyYT** [comment] 2020-08-16 03:23
Possible duplicate of #95 - could've made both of these into one issue

**Comment by drtshock** [comment] 2020-08-16 03:30
Doesn't seem like a duplicate, just separate super specific requests.

**Comment by BennyDoesStuff** [comment] 2021-08-19 20:29
Implemented as of the recent file manager update.

**Closed by BennyDoesStuff** 2021-08-19 20:29 UTC
Labels: feature request, web (core)
