### ISSUE TITLE
Allow uploading JPG files

### ISSUE THREAD

**Issue by RileyDatLord** [Minehut/Meta#225] opened 2020-08-24 16:14 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Allow users to upload JPG files instead of just PNG image files

**How the feature is useful**

This could be useful for server owners who use skript and want to use image on map features and don't understand how to convert a jpg to a png, and it'll be easier to use as we won't have to go through extra steps

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment] 2020-08-24 16:17
1: You can upload pictures 😱 
2: Just look up picture file converter, it takes like 5 seconds and isn't that huge a deal.

**Comment by iGalaxyYT** [comment] 2020-08-24 16:29
Duplicate of #5

**Closed** 2020-08-25 10:21 UTC
Labels: feature request
