### ISSUE TITLE
Minehut per server console permissions (Add them via their email)

### ISSUE THREAD

**Issue by Instinctedd** [Minehut/Meta#911] opened 2022-01-19 16:33 UTC
### Feature request

**Checklist**
- [+] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [+ ] This is not a bug report, support request or plugin request
- [ +] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ]+ This issue does not contain any sensitive information 

**Platform**
 Website

**Describe the feature**

So, Per server permissions, its pretty self explanatory, You can add a user to an individual server, with certain permissions (access to the live console, access to the file manager, ect) this is so if u dont fully trust somebody, but want to give them access to certain parts of your network, you can do that.

**How the feature is useful**

Say if you hired a new developer, and u don't fully trust them, you dont have to risk giving them access to everything, you can just add them to the individual server with certain permissions.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment] 2022-01-19 16:52
Dupe of #13

**Closed** 2022-01-20 20:54 UTC
Labels: feature request
