### ISSUE TITLE
Allow uploading `.mid` files

### ISSUE THREAD

**Issue by SeriousGuy888** [Minehut/Meta#357] opened 2020-11-03 21:18 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Allow uploading files with the extension `.mid`

**How the feature is useful**
While `.midi` files are allowed, `.mid` files aren't allowed to be uploaded to the website and SkQuery's midi features will only recognize `.mid` files.
*(https://github.com/SkQuery/SkQuery/blob/master/src/main/java/com/w00tmast3r/skquery/elements/effects/EffMIDI.java#L52)*

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2020-11-03 21:23
Dupe of #5

**Comment by RichieNy** [comment] 2020-11-04 02:24
Post #5 updated with `.mid`!

**Closed by RichieNy** 2020-11-04 02:24 UTC
Labels: feature request
