### ISSUE TITLE
/ad Togglability

### ISSUE THREAD

**Issue by Budgo** [Minehut/Meta#904] opened 2022-01-09 20:54 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Both

**Describe the feature**

Very simply, add a command to toggle seeing ads. The command can be run from the lobby. Something like /adtoggle or /toggleads.

**How the feature is useful**

This feature would be quite useful for people having general discussion in the lobby. As of now, players cannot see literally anything in the lobby chat through the never-ending torrent of color codes. I timed it, and the longest I went without seeing an ad was 8 seconds. This command would allow people who would like to see ads for servers to do so, and those who would not to not.

However, some trouble arises with the default state of this command. Should players start off seeing ads or not? For my vote, I'd say start off not seeing them, and perhaps have a hologram in spawn saying something along the lines of "to see server ads, type /adtoggle". However, the inverse could also work, and I'm interested in fostering discussion for both sides.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Tringlle** [comment] 2022-01-09 21:20
They already said they aren't doing this. You can use client side mods to block them if you want.

**Comment by Budgo** [comment] 2022-01-09 21:27
Interesting. Did they specify why?

**Comment by aient** [comment] 2022-01-10 19:28
> ### Feature request
> **Checklist**
> 
> * [x]  I have read and agree to the README (found on https://github.com/Minehut/Meta)
> * [x]  This is not a bug report, support request or plugin request
> * [x]  I have searched the Issue Tracker to make sure this is not a duplicate issue
> * [x]  This issue does not contain any sensitive information
> 
> **Platform**
> 
> Both
> **Describe the feature**
> 
> Very simply, add a command to toggle seeing ads. The command can be run from the lobby. Something like /adtoggle or /toggleads.
> 
> **How the feature is useful**
> 
> This feature would be quite useful for people having general discussion in the lobby. As of now, players cannot see literally anything in the lobby chat through the never-ending torrent of color codes. I timed it, and the longest I went without seeing an ad was 8 seconds. This command would allow people who would like to see ads for servers to do so, and those who would not to not.
> 
> However, some trouble arises with the default state of this command. Should players start off seeing ads or not? For my vote, I'd say start off not seeing them, and perhaps have a hologram in spawn saying something along the lines of "to see server ads, type /adtoggle". However, the inverse could also work, and I'm interested in fostering discussion for both sides.
> 
> **Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

I agree with being able to toggle ad messages. I know they are doing something with cooldowns and such but lobby chat is non-existent anymore. We used to be able to have conversations or ask questions in the lobby but now it's just flooded with advertisement spam.

**Comment by Columner** [comment] 2022-01-12 22:37
in issue #353 the main discussion against an advertisement toggle is that:
- it would remove potential players from servers
- it would ruin the purpose of /ad - being to advertise your server without the spam that comes with it

**Comment by aient** [comment] 2022-01-12 23:05
> in issue #353 the main discussion against an advertisement toggle is that:
> 
> * it would remove potential players from servers
> * it would ruin the purpose of /ad - being to advertise your server without the spam that comes with it

If somebody isn't looking to join a server and decided to turn ad messages off, I don't see how they would be affected if they didn't want to join a server and saw an ad message.

**Comment by Tringlle** [comment] 2022-01-12 23:58
> > in issue #353 the main discussion against an advertisement toggle is that:
> > 
> > * it would remove potential players from servers
> > * it would ruin the purpose of /ad - being to advertise your server without the spam that comes with it
> 
> If somebody isn't looking to join a server and decided to turn ad messages off, I don't see how they would be affected if they didn't want to join a server and saw an ad message.

Yes, that makes some sense, but at the same time, it ruins the purpose of /ad. Just like real-life ads, you can't turn those off, can you?

**Comment by aient** [comment] 2022-01-13 00:00
> > > in issue #353 the main discussion against an advertisement toggle is that:
> > > 
> > > * it would remove potential players from servers
> > > * it would ruin the purpose of /ad - being to advertise your server without the spam that comes with it
> > 
> > 
> > If somebody isn't looking to join a server and decided to turn ad messages off, I don't see how they would be affected if they didn't want to join a server and saw an ad message.
> 
> Yes, that makes some sense, but at the same time, it ruins the purpose of /ad. Just like real-life ads, you can't turn those off, can you?

Ads on minehut are different from real life ads. Advertising on minehut is free and free advertising is obviously going to be excessive and annoying. Besides the point, is there any disadvantages of toggling ads? If people don't want to see ads, I don't see why that's an issue.

**Comment by Tringlle** [comment] 2022-01-13 00:03
> > > > in issue #353 the main discussion against an advertisement toggle is that:
> > > > 
> > > > * it would remove potential players from servers
> > > > * it would ruin the purpose of /ad - being to advertise your server without the spam that comes with it
> > > 
> > > 
> > > If somebody isn't looking to join a server and decided to turn ad messages off, I don't see how they would be affected if they didn't want to join a server and saw an ad message.
> > 
> > 
> > Yes, that makes some sense, but at the same time, it ruins the purpose of /ad. Just like real-life ads, you can't turn those off, can you?
> 
> Ads on minehut are different from real life ads. Advertising on minehut is free and free advertising is obviously going to be excessive and annoying. Besides the point, is there any disadvantages of toggling ads? If people don't want to see ads, I don't see why that's an issue.

Its an issue because it drags people away from servers. They already said no, so this argument is useless. Either way, the point of /ad is to get people to join your server, if you turn it off, then there's not really a point to the /ad, as everyone will automatically disable is because they dont wana see them.

**Comment by aient** [comment] 2022-01-13 00:05
> Its an issue because it drags people away from servers. They already said no, so this argument is useless. Either way, the point of /ad is to get people to join your server, if you turn it off, then there's not really a point to the /ad, as everyone will automatically disable is because they dont wana see them.

I don't see how it drags players away from advertised servers. If a player isn't looking for servers to join, they aren't going to join any advertised servers.

**Comment by Tringlle** [comment] 2022-01-13 00:05
> > Its an issue because it drags people away from servers. They already said no, so this argument is useless. Either way, the point of /ad is to get people to join your server, if you turn it off, then there's not really a point to the /ad, as everyone will automatically disable is because they dont wana see them.
> 
> I don't see how it drags players away from advertised servers. If a player isn't looking for servers to join, they aren't going to join any advertised servers.

> if you turn it off, then there's not really a point to the /ad, as everyone will automatically disable is because they dont wana see them.

**Comment by BennyDoesStuff** [comment] 2022-06-30 22:26
Duplicate of #353

**Closed by BennyDoesStuff** 2022-06-30 22:26 UTC
Labels: feature request

**Comment by BennyDoesStuff** [comment] 2022-06-30 22:27
We are looking into further updating server discovery and will revisit the chat ad situation in the future. Being able to toggle ads doesn't stop the spam from happening, just hides it, and we will look into solutions to solve the actual issue at play.
