### ISSUE TITLE
Allow hosts to access the "mcmmo.users" file

### ISSUE THREAD

**Issue by trooboom** [Minehut/Meta#524] opened 2021-02-17 05:27 UTC
### Feature request

**Checklist**
- [ x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x] This is not a bug report, support request or plugin request
- [ x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**
 Website

**Describe the feature**
 Allow hosts the ability to open & edit the file "mcmmo.users" (plugins>mcmmo>flatfile>mcmmo.users). Would allow hosts to edit/transfer the MCMMO user data of all their owned servers.

**How the feature is useful**
 It benefits any servers running MCMMO by allowing hosts to 
 freely change users stats as necessary. Examples include manually increasing/decreasing your own/other players MCMMO Exp., the ability to reset MCMMO stats without resetting the entire server, & the ability to transfer user data freely between Minehut servers.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment] 2021-02-17 14:19
Duplicate of #5

**Closed by Sniped** 2021-02-17 14:19 UTC
Labels: feature request, web (core)
