### ISSUE TITLE
Remove Marketplace Ads on Servers with Purchased Packs

### ISSUE THREAD

**Issue by Tringlle** [Minehut/Meta#593] opened 2021-04-18 03:02 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java & Bedrock
**Describe the feature**

Remove the Minehut MarketPlace ads if the user has purchased a pack from the market place.
**How the feature is useful**

Because some server owners don’t want minehut’s ads. They are quite annoying.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by lolBoi9696** [comment] 2021-04-18 03:42
Just ignore the ads??

**Comment by Blocksnmore** [comment] 2021-04-18 13:25
Semi dupe of #483

**Comment by Sniped** [comment] 2021-04-19 22:53
> Semi dupe of #483

This issue relates to removing marketplace advertisements on servers that have previously purchased a pack, so I wouldn't really call it a dupe.

**Comment by BennyDoesStuff** [comment] 2021-08-19 20:56
Marketplace advertisements should only be sent to free servers.

**Closed by BennyDoesStuff** 2021-08-19 20:56 UTC
Labels: feature request, game

**Comment by Tringlle** [comment] 2021-08-22 01:18
> Marketplace advertisements should only be sent to free servers.

That's not what this is...

If you have a purchased pack like "Moderation Tools" on your server, don't send the marketplace advertisments.

**Comment by Tringlle** [comment] 2021-10-04 02:42
@BennyDoesStuff
