### ISSUE TITLE
Ability to upload .jar plugins

### ISSUE THREAD

**Issue by emopedia** [Minehut/Meta#445] opened 2020-12-25 09:31 UTC
**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

Platform
In-game

I believe we should be able to upload .jar plugins to Minehut servers. This would cause players to not be limited to a number of plugins and cause for some really unique and never seen before servers on Minehut. This is a good idea in my opinion as people who know Java could make their own unique plugins. This is just a suggestion. 

---
Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.

**Comment by Blocksnmore** [comment] 2020-12-25 13:29
This has already been suggested multiple times and won’t be coming soon mainly due to security concerns. You can’t just trust someone you don’t know to upload safe jars

**Comment by LukasmanMHdude** [comment] 2020-12-25 15:28
suprised this hasn't been closed alr

**Comment by Blocksnmore** [comment] 2020-12-25 16:16
Technically a dupe of #5 so if someone could close this that would be good

**Closed** 2020-12-25 18:46 UTC
Labels: duplicate, feature request, web (core)
