### ISSUE TITLE
Option to overwrite files

### ISSUE THREAD

**Issue by aient** [Minehut/Meta#905] opened 2022-01-10 20:12 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website
**Describe the feature**

A check box in the "File Manager Settings" to be able to overwrite files.
**How the feature is useful**

This would be beneficial to people who write their own plugins or skripts as you wouldn't have to delete your old plugin/skript before uploading your latest version. It could also be useful for people writing configs who choose to do it in another environment that saves to their local pc.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CoreyShupe** [comment] 2022-03-08 18:46
Dupe of #778

**Closed by CoreyShupe** 2022-03-08 18:46 UTC
Labels: feature request
