### ISSUE TITLE
Show Ad Cooldown on Rank Features

### ISSUE THREAD

**Issue by killergotrekt** [Minehut/Meta#502] opened 2021-02-03 16:55 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Panel
**Describe the feature**

Add the /Ad Cooldown Time to the Rank Features 
**How the feature is useful**

When it says to Upgrade to a better rank for lowered cooldown, people don't know which rank they should get since the cooldown time isn't listed

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment] 2021-02-04 06:08
Dupe of https://github.com/Minehut/Meta/issues/425

**Closed by Sniped** 2021-02-04 06:08 UTC
Labels: feature request, web (core)
