### ISSUE TITLE
.gif and .lang File Extensions

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#116] opened 2020-08-16 03:44 UTC
### Feature request

**Platform**
 website

**Describe the feature**

.lang and .gif file extension for uploading

**How the feature is useful**

.gif is required for AnimatedFrames plugin.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment] 2020-08-16 03:55
Duplicate of #5

**Closed by drtshock** 2020-08-16 03:55 UTC
Labels: feature request
