### ISSUE TITLE
Op Player Section

### ISSUE THREAD

**Issue by BluBoy3ch0** [Minehut/Meta#338] opened 2020-10-26 04:53 UTC
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

A button / section, possibly in the [Player Section](https://github.com/Minehut/Meta/issues/287) of the dashboard that allows you to op a player from the dash without typing in the op command in console command section. 

**How the feature is useful**

This is useful for server owners who either aren't on the server and need to control who is and isn't op on the fly. Also for people who just started their server and want to op themselves.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2020-10-26 04:54
Dupe of #287

**Comment by BluBoy3ch0** [comment] 2020-10-26 04:55
heck, my bad, guess I didnt search very well

**Comment by Blocksnmore** [comment] 2020-10-26 04:56
Feel free to post the idea you have on that suggestion and close this one

**Closed by Blocksnmore** 2020-10-26 04:56 UTC
Labels: feature request
