### ISSUE TITLE
Releasing old lobbies

### ISSUE THREAD

**Issue by Shlba** [Minehut/Meta#403] opened 2020-11-29 02:03 UTC
**Platform**
Discord, in-game

**Describe the feature**
Release old lobby worlds that aren’t used anymore to the public 

**How the feature is useful**
Allows players to explore the lobbies and find out what they may have missed out on 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Shlba** [comment] 2020-11-29 02:05
I~ mobile is weird, my apologies

**Comment by Sniped** [comment] 2020-11-29 02:05
Do you propose that this should be done via discord?

**Comment by Shlba** [comment] 2020-11-29 02:07
> Do you propose that this should be done via discord?

It can be, if there isn’t a better option. Personally I think a Dropbox link would be more than sufficient

**Comment by PundaChen** [comment] 2020-11-29 02:09
> Do you propose that this should be done via discord?

Mh market

**Comment by drtshock** [comment] 2020-12-02 21:00
Yeah we can do this on the market.

**Comment by honkling** [comment] 2020-12-04 16:32
This would be epic.

**Comment by BennyDoesStuff** [comment] 2021-08-19 20:45
Duplicate of #290

**Closed by BennyDoesStuff** 2021-08-19 20:45 UTC
Labels: feature request, game
