### ISSUE TITLE
Remove all friends.

### ISSUE THREAD

**Issue by ntrogen** [Minehut/Meta#744] opened 2021-08-20 00:00 UTC
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**
In-game

Java

**Describe the feature**
I would like a /friend removeall command to be added to Minehut, upon execution it'll ask you to confirm you want to do the action and then it wipe all of your friends.

**How the feature is useful**
It would be useful to people who have a lot of friends from a long time ago and don't want to remove each and every one of them, example I have 20 pages of friends however I want to clear that list since I only want close friends to be friends on minehut.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment] 2022-06-30 22:31
Duplicate of #115

**Closed by BennyDoesStuff** 2022-06-30 22:31 UTC
Labels: feature request
