### ISSUE TITLE
Making protocolsupport/ViaVersion a default plugin.

### ISSUE THREAD

**Issue by xenitrogen** [Minehut/Meta#329] opened 2020-10-21 19:18 UTC
### Feature request

**Checklist**
- [ ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**

Java

**Describe the feature**

Basically, Most people know that minehut stays up-to-date with minecraft versions, but there's still people that use clients like 1.8 & 1.12 etc & its annoying to see people advertising servers then as soon as you try & connect "Please use 1.16.3"

**How the feature is useful**

This feature would benifit people that dont want to update to the latest version for several reasons such as the pvp update in 1.9.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment] 2020-10-21 19:20
Pretty sure these plugins can mess up a lot of stuff on servers specifically made for 1.16, they can also cause unnecessary lag

**Comment by AdxmGG** [comment] 2020-10-21 19:22
I think there should be a toggle-able button on the dashboard such as **`Allow Older Clients`** which would allow these rather than them being pre installed.

**Comment by PundaChen** [comment] 2020-10-21 19:23
> I think there should be a toggle-able button on the dashboard such as **`Allow Older Clients`** which would allow these rather than them being pre installed.

Isn't this the same as just going to the plugins tab and installing it?

**Comment by AdxmGG** [comment] 2020-10-21 19:24
> Isn't this the same as just going to the plugins tab and installing it?
Not everyone knows how to allow older versions to join, plus it's just easier. Most users already want older versions to join, why not make it easier for them?

**Comment by Sniped** [comment] 2020-10-21 19:33
I don't believe installing the plugin by default is an efficient way of going about users wanting multiple versions on their server. Like I said below in response to @AdxmGG, it could be apart of an interactive process where Minehut recommends you plugins to install if you want x on your server. I don't have a great idea of how this could be implemented as this was a rough idea, however I believe this is a better way of going about this issue. 

> Not everyone knows how to allow older versions to join, plus it's just easier. Most users already want older versions to join, why not make it easier for them?

In my opinion, this shouldn't necessarily be a button on the core panel, rather it could be apart of an interactive process where Minehut could recommend plugins for you to install on your server when you first create an account/create a server. As it stands right now, with just a quick YouTube search I end up at [this](https://youtu.be/o7QQcW2MOQ0) video that shows how to install the necessary plugins.

**Comment by Shlba** [comment] 2020-10-21 23:11
I think people just want an extra plugin slot...lol

**Comment by LukasmanMHdude** [comment] 2020-10-22 00:37
I agree with shilba on this one. I do think that all the via plugins should be one, but that's for a separate issue.

**Comment by LukasmanMHdude** [comment] 2020-10-22 00:39
This is a dupe of #308 btw.

**Comment by Sniped** [comment] 2020-10-22 00:41
This suggestion is suggesting making ViaVersion / ProtocolSupport a default plugin, not excluding these plugins from the plugin limit.

**Comment by iGalaxyYT** [comment] 2020-10-22 01:00
An interesting way of doing this could be a "Suggested Plugins" area of the plugins page, which suggests plugins for you to install rather than having them installed by default, which some users may not want.
Examples:

"Allow older Minecraft versions to connect to your Minehut server"
- ViaVersion
- ViaBackwards

"Easy-to-use commands for your Minehut server"
- EssentialsX etc.

**Comment by LukasmanMHdude** [comment] 2020-10-22 01:03
> An interesting way of doing this could be a "Suggested Plugins" area of the plugins page, which suggests plugins for you to install rather than having them installed by default, which some users may not want.
> Examples:
> 
> "Allow older Minecraft versions to connect to your Minehut server"
> 
> * ViaVersion
> * ViaBackwards
> 
> "Easy-to-use commands for your Minehut server"
> 
> * EssentialsX etc.

Yea I made that suggestion (#243) but 00 said it could be "favoritism" (imo its not)

**Comment by xmuel** [comment] 2020-11-01 22:52
> I think there should be a toggle-able button on the dashboard such as **`Allow Older Clients`** which would allow these rather than them being pre installed.

I'm not really a fan of any plugins becoming default options like some mentioned above. Instead, I'd prefer this ^ as it could be something Minehut itself does so its easier to maintain and manage to ensure it doesn't cause bugs like Protocol often does.

**Comment by xenitrogen** [comment] 2020-11-08 16:20
> > I think there should be a toggle-able button on the dashboard such as **`Allow Older Clients`** which would allow these rather than them being pre installed.
> 
> I'm not really a fan of any plugins becoming default options like some mentioned above. Instead, I'd prefer this ^ as it could be something Minehut itself does so its easier to maintain and manage to ensure it doesn't cause bugs like Protocol often does.

Completely agree with you.

**Comment by LukasmanMHdude** [comment] 2020-11-08 16:22
It would also be nice to instead add a slider of some sort that allows you to select more specific versions

**Comment by xenitrogen** [comment] 2020-11-15 09:01
> It would also be nice to instead add a slider of some sort that allows you to select more specific versions
Agreed

**Comment by Vocallity** [comment] 2020-11-15 11:21
> It would also be nice to instead add a slider of some sort that allows you to select more specific versions

+1

**Comment by killergotrekt** [comment] 2020-11-15 18:41
disagree since some servers don't want 1.8+ compatibility

**Comment by Tringlle** [comment] 2021-05-28 14:48
> disagree since some servers don't want 1.8+ compatibility

Did you just skip over the entire thread…?

**Comment by Saturn5Vfive** [comment] 2021-05-28 14:53
legacy compatability is not nessesary for all servers

**Comment by BennyDoesStuff** [comment] 2021-08-19 20:42
ViaVersion is currently a default plugin. Custom versions will be coming out soon anyways so this will not be feasible.

**Closed by BennyDoesStuff** 2021-08-19 20:42 UTC
Labels: feature request, web (core)
