### ISSUE TITLE
Whitelist & banned server mayham

### ISSUE THREAD

**Issue by lolBoi9696** [Minehut/Meta#514] opened 2021-02-12 07:55 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**

Both

**Describe the feature**

make it so if your not whitelisted it tries another server same if your banned on whatever server you tried to connect to

**How the feature is useful**

Well we wouldn't have to wait 5 secs just to manually join another server and it could take a long time to find a non whitelisted server

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LukasmanMHdude** [comment] 2021-02-12 07:59
dupe of #10

**Closed** 2021-02-12 15:30 UTC
Labels: duplicate, feature request, game
