### ISSUE TITLE
Server Voting

### ISSUE THREAD

**Issue by Mqdelyn0** [Minehut/Meta#610] opened 2021-04-29 04:43 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-Game Both / Panel

**Describe the feature**

This could help with the struggle to find good servers, But maybe add a voting system? Players can vote (1/day limit) on the server they like the most, And on the panel and in-game through another GUI, There would be a list of servers and their votes, sorted from top votes to lowest votes.

**How the feature is useful**

It could help underrated servers grow, And help players find good servers

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by tarna** [comment] 2021-04-29 04:49
How would this work? Would a player need to have their account linked to be able to vote through the panel? And would the number reset every now and then? Like monthly.  Also this will probably make all current top servers at the top of that list since they have a lot of players to vote.

**Comment by Mqdelyn0** [comment] 2021-04-29 04:51
> How would this work? Would a player need to have their account linked to be able to vote through the panel? And would the number reset every now and then? Like monthly. Also this will probably make all current top servers at the top of that list since they have a lot of players to vote.

I never really thought of this LMAO. We could exclude servers with a high average or X votes in X days, To make it fair for the actually good servers that's trying to grow, But simply can't. Votes would reset monthly, Or bi-weekly as holy crap Minehut servers come and go too fast 🤣

**Comment by DaRealMinecraftexpert** [comment] 2021-04-29 04:52
I believe Server Bumping was Mentioned before, but I don't remember much about it

**Comment by quick007** [comment] 2021-04-29 05:02
dupe of #372

**Comment by DaRealMinecraftexpert** [comment] 2021-04-29 05:05
> dupe of #372, #352, and #418

So I was remembering Correctly?

**Closed** 2021-04-29 10:07 UTC
Labels: feature request
