### ISSUE TITLE
New Ranks (MT)

### ISSUE THREAD

**Issue by muelr** [Minehut/Meta#583] opened 2021-04-06 19:14 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Both

**Describe the feature**

New [TWITCH] and [MEDIA] rank added. Probably like &5 for Twitch and I'm not sure for [MEDIA], although up for discussion. 

**How the feature is useful**

Some media members are twitch creators and are sometimes harassed for not meeting the requirements as they are not a youtube creator. Since our only in game rank for the Media Team is [YOUTUBE] the addition of these 2 additional ranks would help avoid confusion. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment] 2021-04-06 19:19
Are you suggesting that [YOUTUBE] is replaced with [MEDIA]? If so, I believe that would be similar to https://github.com/Minehut/Meta/issues/528.

**Comment by Centrect** [comment] 2021-04-06 22:49
dupe of #528 but as a possessor of the youtube rank it would be so much more convenient to have this system, and would save a lot of angry dms that I receive!

**Comment by muelr** [comment] 2021-04-07 09:41
Yeah, suggesting that 2 new ranks are added as oppose to having a media rank replace the YouTube rank as mentioned in that issue.

**Comment by xenitrogen** [comment] 2021-04-07 23:22
I think there should just be one rank which is **[MEDIA]**

**Comment by honkling** [comment] 2021-04-10 23:07
don't really need two identical ranks with different prefixes, especially since the ranks belong to the same group. i'd much rather just have [media] because then we wouldn't have to implement a new rank or manage who's from youtube gaming and who's from twitch

**Closed** 2021-11-29 20:03 UTC
Labels: feature request, game
