### ISSUE TITLE
If a players server doesn't start their server every (x) days they will lose their server name, but players can use credits to keep their server name for as long as they want

### ISSUE THREAD

**Issue by KingKline** [Minehut/Meta#554] opened 2021-03-16 18:46 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
With minehuts rise in new players server names are getting harder and harder to find. With some new players picking a server name using the server once and never playing on minehut again.

If a server isn't activated for certain time period lets say 30 days the server will become nameless allowing other people to use the name. A server that is nameless won't be able to start again until a new name is picked.

Now people who use minehut a lot don't always play on their server every 30 days. This is where you can buy a server name with credits. For x amount of credits your server name will always belong to that account. You can remove the server name from your account but will not receive any credits back.

**How the feature is useful**
This feature is helpful to new players with them being able to easily create a server without having to find an available server name. (yes some names will still be used but not at the scale it is now)

For active users this is no issue because as long as there server gets activated in x days they keep their server name.

For long time minehut players who have og server names they can claim them only if it is worth it for them. If a minehut player is just keeping a servername but has no use for it they will most likely not pay credits for it.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BluBoy3ch0** [comment] 2021-03-16 18:50
Definitely a feature Minehut should implement. Maybe it could even be that servers that haven't been used in a very long time will get an email warning, and if nothing is done, then maybe the server just poofs. Would clear up inactive servers and just help to recycle servers.

**Comment by quick007YT** [comment] 2021-03-16 19:33
dupe of #189 I also don't think you should have to or be able to pay to keep a server name longer, just use it lol

**Comment by Sniped** [comment] 2021-03-16 19:35
> dupe of #189 I also don't think you should have to or be able to pay to keep a server name longer, just use it lol

The implementation of server name claiming that you suggested here can be posted on that issue. I'm closing this issue as a dupe of that one.

**Closed by Sniped** 2021-03-16 19:35 UTC
Labels: feature request
