### ISSUE TITLE
Easy to use players tab on website.

### ISSUE THREAD

**Issue by Prorickey** [Minehut/Meta#575] opened 2021-04-05 05:01 UTC
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Basically, a tab in the console that brings up a list of players. You should be able to click on each player in the list and have options such as ban, kick, op and whitelist. At the top of the list, there could be a section with some general options such as toggling the whitelist and maybe a kick-all button. 

**How the feature is useful**

It is useful for players that are not very knowledgeable on how to work servers. Instead of having to op themselves and use in-game commands which can be a hassle for a lot of players, they can use this feature.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by MiginsMC** [comment] 2021-04-05 05:04
Closing due to this being a dupe of #287.

**Closed by MiginsMC** 2021-04-05 05:04 UTC
Labels: feature request
