### ISSUE TITLE
A “Recent Servers” tab.

### ISSUE THREAD

**Issue by Sunni05** [Minehut/Meta#516] opened 2021-02-13 03:59 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ ] This issue does not contain any sensitive information 

**Platform**

Both 
**Describe the feature**

There could be a tab somewhere, like a gui, when it comes up, it displays your 5 most recent servers, if you click them it will take you to that server, or something along those lines.
**How the feature is useful**

It’s useful for those people who forgot which server they were on, and want to go back.
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment] 2021-02-13 05:09
Dupe of https://github.com/Minehut/Meta/issues/337

**Closed by Sniped** 2021-02-13 05:09 UTC
Labels: feature request
