### ISSUE TITLE
A message to the MineHut Staff/Developers

### ISSUE THREAD

**Issue by BlueSky-fur** [Minehut/Meta#774] opened 2021-08-31 12:52 UTC
### Feature request

**Checklist**
- [ x ] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x ] This is not a bug report, support request or plugin request
- [ x ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x ] This issue does not contain any sensitive information 

**Platform**

Both.
### **Describe the feature**

I highly suggest you should change it so when you create a Minecraft server its in whitelist mode automatically, when i use join random server every second server i join there's at least one guy that tries to convince me hes an absolute "Minecraft" expert and spams "LEAVE LEAVE Leave leave now leeeeeeave".

But then they don't even know how to kick you and don't even know what "OP" means.

Most People dont even know how to administrate an server and then get pretty toxic and insulting (Insulting Peoples Mothers, or the peoples in general with hefty stuff and N-Word crap.) just because their server is for friends only, but then they dont even know what a whitelist is.

 

Or maybe add a feature that when you are in the process of creating a new server a Pop-Up appears that has a 15-20 Second timer where Important Info like Links to a Whitelist Tutorial appears, and after 15-20 Seconds they can click on a button that for example says "I've Understood the text and know how to turn on a whitelist" or something else.

 

I dont think its good that Newly-Created servers have the whitelist disabled by default, ive played and looked at servers (Java and Bedrock) for 3 Days now, and heared more Insults than i did in my School-Days.  

Also maybe overhaul the Join Random Server thing so you dont join whitelisted servers because atleast on Java Edition you then need to re-connect to Minehut.

### **How the feature is useful**

People would benefit from it to either learn what a whitelist is and use it correctly (since most people as described dont know what a whitelist is.)

and then they can stop Insulting people as mentioned a few lines up. 
Its honestly just not good that you join a Server that is "private" and then get called the N-word and much much worse other stuff.
 
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment] 2021-09-01 17:39
Duplicate of #427

**Closed by BennyDoesStuff** 2021-09-01 17:39 UTC
Labels: feature request

**Comment by BlueSky-fur** [comment] 2021-09-01 18:06
> Duplicate of #427

sorry, when i searched this didnt came up.
