### ISSUE TITLE
Server names

### ISSUE THREAD

**Issue by Jumpyy123** [Minehut/Meta#648] opened 2021-06-09 20:16 UTC
**Platform**
 Both

**Describe the feature**

I have an idea about server names... A lot of people are trying to get some names for their servers but a lot of them are taken from FREE servers that haven't been up in years. I think there should be something where, if a server hasn't been up for a year or a certain time period, that server name becomes available. 

**How the feature is useful**

It would benefit everyone... The server names that haven't been used in years, why would that matter to them? it's been years since they've lifted the server.

 

Just a suggestion, let me know what you think 🙂 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2021-06-09 20:27
Dupe of #189

**Comment by BennyDoesStuff** [comment] 2021-08-19 21:00
Duplicate of #189

**Closed by BennyDoesStuff** 2021-08-19 21:00 UTC
Labels: feature request
