### ISSUE TITLE
File paths in search bar

### ISSUE THREAD

**Issue by quick007** [Minehut/Meta#378] opened 2020-11-12 16:39 UTC
**Platform**
web (core)

**Describe the feature**
When ur in the file manager add the names in the search bar, so this would look like https://minehut.com/dashboard/file-manager/[servername]/[folders here, i.e. `plugins/skript/skripts/eco.sk`]

**How the feature is useful**
This would allow people to easily navigate file explorer using the forward and back buttons on their mice/browser.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by mekb-turtle** [comment] 2020-11-23 05:56
:+1: This is really helpful. Also same for the tabs like plugins.
I reckon it could be something like `https://minehut.com/dashboard/server/[server-name]/file-manager/[file path]` and `https://minehut.com/dashboard/server/[server-name]/appearance`

**Comment by ManagePasswords** [comment] 2020-12-10 14:05
> 👍 This is really helpful. Also same for the tabs like plugins.
> I reckon it could be something like `https://minehut.com/dashboard/server/[server-name]/file-manager/[file path]` and `https://minehut.com/dashboard/server/[server-name]/appearance`

I would say something like `https://minehut.com/dashboard/server/[server-name]/file-manager/?path=[file-path]` would be better

**Comment by DereC4** [comment] 2021-01-29 22:23
I agree this would be a really good quality of life change; for example if one wanted to quickly navigate to permsex directory

**Comment by LukasmanMHdude** [comment] 2021-01-29 22:52
> I agree this would be a really good quality of life change; for example if one wanted to quickly navigate to permsex directory

or just skripting in general

**Comment by BennyDoesStuff** [comment] 2021-08-19 20:43
Duplicate of #45

**Closed by BennyDoesStuff** 2021-08-19 20:43 UTC
Labels: feature request, web (core)
