### ISSUE TITLE
Bring back /server in game

### ISSUE THREAD

**Issue by BlakeH2208** [Minehut/Meta#439] opened 2020-12-17 06:32 UTC
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**
 Java

**Describe the feature**
 allow the feature where we can use /server from a player server to let people easily travel between servers

**How the feature is useful**
 it would make it so much easier to travel between servers and would make it possible to make a network of minehut servers

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment] 2020-12-17 08:13
This is a duplicate of #119 (planned)

**Closed** 2020-12-17 16:38 UTC
Labels: duplicate
