### ISSUE TITLE
Hide users in lobby

### ISSUE THREAD

**Issue by PundaChen** [Minehut/Meta#135] opened 2020-08-16 13:53 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Ingame

**Describe the feature**
Ability to hide players in the lobby

**How the feature is useful**
Reduces lag for users 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment] 2020-08-16 13:55
Hey, this issue is a duplicate of #24

**Closed by jellz** 2020-08-16 13:55 UTC
Labels: duplicate, feature request
