### ISSUE TITLE
Coop

### ISSUE THREAD

**Issue by abra6325** [Minehut/Meta#953] opened 2022-03-26 06:59 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Java ingame

**Describe the feature**

Can Minehut have Coop servers so 2 people can edit the files and add pluginsto the same server?
**How the feature is useful**

Server developers
---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by erenkarakal** [comment] 2022-03-26 09:41
sub-users are already suggested

**Comment by GStudiosX2** [comment] 2022-03-26 12:20
Dupe of #13 ?

**Comment by Tringlle** [comment] 2022-04-13 17:38
Yeah, it would be considered that. Someone close this as it is a duplicate.

**Comment by BennyDoesStuff** [comment] 2022-06-30 22:28
Duplicate of #13

**Closed by BennyDoesStuff** 2022-06-30 22:28 UTC
Labels: feature request
