### ISSUE TITLE
Add more plugin slots for the free plan servers so people can  improve their servers 

### ISSUE THREAD

**Issue by herofireYT** [Minehut/Meta#607] opened 2021-04-28 15:27 UTC
hello minehut staff members :

[ ] add  more plugin slots for the free plan servers . so this will be usefull for people that cannot afford the prem servers . and it will help to improve servers .
[ ] this feature will improve the ingame servers and for both platforms (java&bedrock)
[ ] make it so plugins like essentails plugins (essentails chat/essentails spawn....) count as 1 pugin and that would make it easier for new people to servers. 0
[ ] make it so vault is a built in evry server plan

**Comment by quick007** [comment] 2021-04-28 15:30
still didn't follow the format

**Comment by DaRealMinecraftexpert** [comment] 2021-04-28 16:01
Imma leave this here https://github.com/Minehut/Meta/issues/new/choose

**Comment by Sniped** [comment] 2021-04-28 16:38
This is a duplicate of #606 and doesn't follow the format. Please use the format linked here when making an issue.

**Closed by Sniped** 2021-04-28 16:38 UTC
Labels: feature request
