### ISSUE TITLE
Random Server MOTDs

### ISSUE THREAD

**Issue by Parsafari** [Minehut/Meta#428] opened 2020-12-12 20:13 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Java

**Describe the feature**
I see a lot of servers where every time you refresh the page a random MOTD appears. I think it would be cool to have this feature added to minehut.

for example:

MOTD 1 | chance: 20% | the best server on earth!

MOTD 2 | chance: 20% | who wants free diamonds?

MOTD 3 | chance: 20% | join our discord: <link>

MOTD 4 | chance: 20% | join for 10 years of good luck

MOTD 5 | chance: 20% | new season out!

then it randomly selects a MOTD like every 5 seconds.
 

**How the feature is useful**
It helps the servers be cooler.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment] 2020-12-12 20:31
Should the list that random MOTDs are selected from be created by the server owner?

**Comment by Sniped** [comment] 2020-12-12 20:33
I’ve also edited your post to exclude the suggestion of increasing the limit as that was suggested in #42

**Comment by LukasmanMHdude** [comment] 2020-12-12 21:09
technically dupe of #195, although this one goes more in depth with the feature

**Comment by Parsafari** [comment] 2020-12-13 16:50
> Should the list that random MOTDs are selected from be created by the server owner?

yeah like there will be a + button where you can add more MOTDs to the list

**Closed** 2021-07-15 21:08 UTC
Labels: feature request, game, web (core)
