### ISSUE TITLE
Gifted Credits

### ISSUE THREAD

**Issue by IWolfZ** [Minehut/Meta#383] opened 2020-11-15 06:49 UTC
**Checklist**
- [yes] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [yes] This is not a bug report, support request or plugin request
- [yes] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [yes] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
Minehut should add a way to buy credits from one console to another console. Adding this to Minehut would be super useful if someone wants to buy you credits for your server or something without having to give them the login info of your Minehut panel which is risky. 

**How the feature is useful**
Its useful because people can buy credits to another panel

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Blocksnmore** [comment] 2020-11-15 15:20
I would change the title to something like “buying other servers credits” since gifting credits is confirmed not happening because of the fact that people can vote and transfer the credits to a panel and never have to pay for stuff like mh unlimited

**Comment by LukasmanMHdude** [comment] 2020-11-15 19:55
Dupe of #377 and #274

**Comment by Sniped** [comment] 2020-11-15 19:56
Closing this as dupe of #377

**Closed** 2020-11-15 19:56 UTC
Labels: feature request
