### ISSUE TITLE
Great performance opportunity

### ISSUE THREAD

**Issue by Reimagine-matias-s** [Minehut/Meta#545] opened 2021-03-03 13:02 UTC
### Feature request
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-Game mostly probably

**Describe the feature**

Migrate or offer the option to use PurpurMC instead of Paper. 

Migrating or offering the option to have
**How the feature is useful**

I believe this would be a great idea as Purpur runs wayyy faster than Paper with unity's starlink (I believe that's the name) engine. Despite this, it has the core files of paper and does not change almost any features or functionality. The main differences consist of more options and way better performance as you see by the graphs. Whether you add more player slots or keep it the same, it would provide direct performance a feature benefits for everyone and would be a change that Minehut benefits from. I learned this from a competitor hosting and seemed to great of an idea not to share please consider it 👍🏼 . very well documented too https://purpur.pl3x.net/ . This project is finally public and have been in development for a while
![image](https://user-images.githubusercontent.com/69017144/109809903-dc1d2180-7bf6-11eb-86d7-cdb7d31d030e.png)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Reimagine-matias-s** [comment] 2021-03-03 13:04
It is called "starlight" my bad. With the rewrite done by unity, it functions for lightweight application. This is perfect for Minecraft and considered "lightweight" when compared to massive server operations.

**Comment by Blocksnmore** [comment] 2021-03-03 13:45
Dupe of #492

**Comment by Reimagine-matias-s** [comment] 2021-03-03 14:09
wait why did that post get flamed? people obviously don't know the benefits purpur brings, I believe this post represents it better but thanks for pointing that out . I think this is a change that many people would enjoy on minehut. very odd

**Comment by Sniped** [comment] 2021-03-03 17:51
As an admin said on that issue, customizations where you can change the jar of the server may come in the future.

**Closed by Sniped** 2021-03-03 17:51 UTC
Labels: feature request
