### ISSUE TITLE
Display Memory / CPU usage

### ISSUE THREAD

**Issue by farwl** [Minehut/Meta#84] opened 2020-08-16 03:11 UTC
### Feature request

**Platform**
Website

**Describe the feature**

Add a memory / CPU usage chart somewhere on the server dashboard. Would be cool to see your RAM / CPU usage without having to install Essentials to use the /uptime command to see your free memory.

**How the feature is useful**

QOL

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by drtshock** [comment] 2020-08-16 03:33
Duplicate of #9

**Closed by drtshock** 2020-08-16 03:33 UTC
Labels: feature request
