### ISSUE TITLE
!googlify command to encourage users to use Google for simple yet hard-to-explain-over-text questions

### ISSUE THREAD

**Issue by LouisLit** [Minehut/Meta#822] opened 2021-10-13 21:49 UTC
### Feature request

**Checklist**
- [ x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ x] This is not a bug report, support request or plugin request
- [ x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**
 N/A

**Describe the feature**
  A command that takes a given command argument and turns it into a Google search link. Example:` !googlify good Minecraft plugins`. Result: https://google.com/search?q=good+Minecraft+plugins

**How the feature is useful**
 the feature is useful because it outlines how useful Google is compared to simply asking a sometimes redundant and less opinion based question. Another example of a redundant question that the command could be used to answer in a trivial way would be: "How do I set up WorldGuard?" Or "How do I setup spawn protection?"  The command is exceptionally useful for questions which require a lot of explaining, which is way less practical to do over Discord and easier if the user clicks the link generated by the command arguments of another user and finds a YouTube video on how to do it.

Further info:
I have created this command myself as it's relatively simple, only using the command arguments and splitting them into an array with a whitespace, and then appending all of them together again with a "+" in between.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by BennyDoesStuff** [comment] 2022-06-30 20:08
Duplicate of #306

**Closed by BennyDoesStuff** 2022-06-30 20:08 UTC
Labels: feature request
