### ISSUE TITLE
bring back white theme

### ISSUE THREAD

**Issue by Randoms-Squad** [Minehut/Meta#719] opened 2021-08-08 18:53 UTC
### Feature request

**Checklist**
- [ x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [ ] This is not a bug report, support request or plugin request
- [ ] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [ x] This issue does not contain any sensitive information 

**Platform**
 website

**Describe the feature**
Bring back white theme 

**How the feature is useful**
 i use it down to my learning disability and now my filters don't work on the dashbord anymore and I have to get my sister to help me if this is not bringing back even if it is a hidden feature what be better or i'll just go and look some were elis 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by CodingWRLD** [comment] 2021-08-08 20:49
dupe of #692

In my opinion, I think the new dashboard look is cool. And I never used the light theme anyway, it was like receiving a flashbang. Maybe in the future, they can add more themes and etc. But honestly, this should be the lowest priority. The new-look is fine, and just takes getting used to.

Leaving a website because of a theme **you** as well.... I mean look at google. They had a white theme for ages. And they only just released a dark mode feature... You have to live with it, and minehut should have bigger plans than changing their theme to suit everyone.

**Comment by Randoms-Squad** [comment] 2021-08-08 21:16
but it was an option black or white

**Comment by honkling** [comment] 2021-08-15 14:10
> In my opinion, I think the new dashboard look is cool. And I never used the light theme anyway, it was like receiving a flashbang.
...did you read why they wanted it back? They have a disability, they NEED light theme. I don't really think "I don't like it" is a good reason not to add it, going up against "I have a disability"

**Closed** 2021-08-16 13:50 UTC
Labels: feature request
