### ISSUE TITLE
Market Advertisements

### ISSUE THREAD

**Issue by IWolfZ** [Minehut/Meta#591] opened 2021-04-16 21:17 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
 Both

**Describe the feature**
 My feature is a way to remove your advertisements, there so annoying especially in servers where people are trying to play and you just get messages like "Battle on your on PitPvP Server begin by downloading here". wasn't something similar done in #483 but you guys really didn't. And it's in paid plan servers, Why do you advertise especially in paid plan servers it makes no sense, and it's annoying to see it in chat, and stop advertising your stream like "Deepth is now going to FLOSS **OMG** FORTNITE DANCE LETS DANCE TUNE IN NOW" its legit cringe and saying "[ProTip] grow your server at light speed with lobby rank" like are you that money hungry? Or just make it an option where you can disable this and just advertise it in the lobbies only.

**How the feature is useful**
 How this would be useful to many servers is because it's spamming and no one really cares about it, advertising your market stuff is a waste, and it's not even useful! REMOVED IT!!!

Image of annoying stuff:
![image](https://user-images.githubusercontent.com/44043990/115084857-11dc4800-9ecf-11eb-87ca-3668f005ef66.png)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by quick007** [comment] 2021-04-16 21:19
dupe of #483, which was marked as done apparently lol

**Comment by IWolfZ** [comment] 2021-04-16 21:34
> dupe of #483, which was marked as done apparently lol

How is this a dupe of urs? If its marked as done then its something different

**Comment by Blocksnmore** [comment] 2021-04-16 21:39
> > dupe of #483, which was marked as done apparently lol
> 
> How is this a dupe of urs? If it's marked as done then it's something different. and read it and u would understand

Because its marked as done doesn’t mean its something else, the patch may have not worked for example

**Comment by IWolfZ** [comment] 2021-04-16 22:01
> Because its marked as done doesn’t mean its something else, the patch may have not worked for example

Yes the "patch" that happened "didn't" work obvs because it goes on all servers totally didn't work

**Comment by MiginsMC** [comment] 2021-04-17 01:32
This is a dupe of #483 as stated above. If you think that issue should be reopened, feel free to comment on it.

**Closed by MiginsMC** 2021-04-17 01:32 UTC
Labels: feature request
