### ISSUE TITLE
Forums - Allowing us to lock our own posts

### ISSUE THREAD

**Issue by Bevji** [Minehut/Meta#670] opened 2021-07-01 15:51 UTC
### Feature request

**Checklist**
- [X] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [X] This is not a bug report, support request or plugin request
- [X] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [X] This issue does not contain any sensitive information 

**Platform**
 Minehut Forums

**Describe the feature**
 Allow users to lock their own posts instead of having to request a staff member to do it for them.

**How the feature is useful**
 Instead of hiding, we should have the option of locking our own posts too. Like there is no reason for us not to have that option. 

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by LogicalSpider** [comment] 2021-07-01 15:52
Also, I know I probably shouldn't send this under this one but this took me way too long to figure out how to post something like this. The old way was better through the discord ;-;

**Comment by OGContent** [comment] 2021-07-01 16:07
There is a reason mods don't just close issues, first they put a suggestion to the admins or whatever, second the suggestion is not good or cannot be done, if you close ur issues no one would able to make a suggestion to ur suggestion, so its better to leave it for the staff

**Comment by OGContent** [comment] 2021-07-01 16:14
i agree, for those who read from the discord meta i read the thing wrong

**Comment by tarna** [comment] 2021-07-01 23:37
dupe of #557

**Closed** 2021-07-01 23:39 UTC
Labels: feature request
