### ISSUE TITLE
plugin for buycraft (using credit),Plugin to donate credit

### ISSUE THREAD

**Issue by Reketer** [Minehut/Meta#394] opened 2020-11-25 04:09 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Java

**Describe the feature**
1-because i dont own paypal way to earn money,credit (plugin for buycraft (using credit)
so each $1 = 160 credit
800/5=160 credit
work similar to buycraft (tebex) but instead of using paypal method 
is using the credit you have in minehut
2-way to support server owner (Plugin to donate credit)

**FAQ:**
the money goes to minehut and the server owner gets credits?
yes
**How the feature is useful**
This is useful because it will help add way to upgrade server and support owner, it will help with people that dont have paywal,etc (way to earn credit).

**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Shlba** [comment] 2020-11-25 08:41
Clone of #377

**Comment by Reketer** [comment] 2020-11-25 08:46
> Clone of #377

first plugin not clone 
second plugin similar to him
he clone  #274 ^,^

**Comment by Shlba** [comment] 2020-11-25 09:16
regardless it has already been suggested in some form or another

**Comment by Sniped** [comment] 2020-11-25 21:52
This suggestion can be added onto #377 and is very similar to it, thus I am going to close this as a duplicate of it. Please comment additional features you would like a credit donation feature to include on that issue.

**Closed by Sniped** 2020-11-25 21:52 UTC
Labels: feature request
