### ISSUE TITLE
Custom server list icons.

### ISSUE THREAD

**Issue by ikeyIX** [Minehut/Meta#672] opened 2021-07-04 17:39 UTC
Hey, I don't know if there is a reason behind why you cant customize server list icons but I have an suggestion.

A suggestion would be for 500 credits you could buy a perm server list icon customization like one of the server icons in the minehut lobby but for the server list where you can import custom images or use minehut default icons. And for the servers who don't want to buy it, you could use one of the default minehut icons, make it like a blue minehut, a red minehut, etc.

Again I'm still not sure if its doable but it would be so cool to see a new feature in Minehut for more customization like this!

Please tell me if its doable since if it is me and others would be so hyped to see this change.

Thanks!

**Comment by tarna** [comment] 2021-07-04 17:41
You didn't use the correct format and this is also a dupe of #419

**Comment by BennyDoesStuff** [comment] 2021-09-10 19:31
Duplicate of #419

**Closed by BennyDoesStuff** 2021-09-10 19:31 UTC
Labels: feature request
