### ISSUE TITLE
Stop ad spam in lobbies

### ISSUE THREAD

**Issue by LukasmanMHdude** [Minehut/Meta#129] opened 2020-08-16 04:24 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Ingame, both

**Describe the feature**
Make it so that if someone posts the same ad over a certain amount of time it will block the message. (i.e. if you spam "/join mygreatserver today" 3 times within 1 minute, it will block the message. (

**How the feature is useful**
Reduces lobby spam

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by jellz** [comment] 2020-08-16 04:26
Hey, in the future remember to fill the checkboxes like `[x]` not `[x ]`. If you're not sure, you can just submit the issue with empty checkboxes then click them afterwards. The important thing is that you follow the steps in the checklist!

**Comment by LukasmanMHdude** [comment] 2020-08-16 05:36
> Hey, in the future remember to fill the checkboxes like `[x]` not `[x ]`. If you're not sure, you can just submit the issue with empty checkboxes then click them afterwards. The important thing is that you follow the steps in the checklist!

Ok, thanks. This was my first so I wasen't really sure on how to make it.

**Comment by Double0negative** [comment] 2020-09-12 09:08
Closing as dupe of #245 because it is more generic and broad in scope.

**Closed by Double0negative** 2020-09-12 09:08 UTC
Labels: duplicate, feature request, game
