### ISSUE TITLE
Claiming unused server names

### ISSUE THREAD

**Issue by MrTibo1** [Minehut/Meta#464] opened 2021-01-05 21:48 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

Website

**Describe the feature**

Allow people to request claiming a used server name. Something like Reddit where people can request to claim an unused reddit community to make it their own.

**How the feature is useful**

A lot of server names are taken by squatters and are put on unused servers, and some people might want a cool unique name for themselves only finding out it's already claimed by some random abandoned server. This would open up the oppurtunity to claim a cool name if it is not used (a server being started like once every couple weeks, probably a player checking out if there is something cool to find, would indicate a server being unused) and grow their own community because the name would be a better fit for what they make and easier to recognize and remember.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by Sniped** [comment] 2021-01-05 21:55
Dupe of https://github.com/Minehut/Meta/issues/189

**Closed by Sniped** 2021-01-05 21:55 UTC
Labels: feature request
