### ISSUE TITLE
New 

### ISSUE THREAD

**Issue by ikeyIX** [Minehut/Meta#715] opened 2021-08-06 20:40 UTC
### Feature request

**Checklist**
- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**
Website

**Describe the feature**
What would be good is new Catagories for servers. For example having 'Economy', 'Survival' and more would really help in servers.

**How the feature is useful**
It can show its a Survival server instead of an SMP. SMPs are more with no plugins and more anarchy while Survival server are different! + It can show the server uses Economy with the Economy section. It will help on the Website Server List if you're trying to find a server to play.

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by DaRealMinecraftexpert** [comment] 2021-08-07 04:49
There's already Server Tags on MH. They just don't have any Resemblance ingame.

**Comment by Sniped** [comment] 2021-08-08 19:31
The issue this belongs on is #627

**Comment by BennyDoesStuff** [comment] 2021-08-20 16:49
Duplicate of #627

**Closed by BennyDoesStuff** 2021-08-20 16:49 UTC
Labels: feature request
