### ISSUE TITLE
Automatically delete messages that advertises someone's server without using /ad and automatically send the player a message telling them to use /ad

### ISSUE THREAD

**Issue by MGSuco** [Minehut/Meta#506] opened 2021-02-05 11:25 UTC
### Feature request

**Checklist**
- 

- [x] I have read and agree to the README (found on https://github.com/Minehut/Meta)
- [x] This is not a bug report, support request or plugin request
- [x] I have searched the Issue Tracker to make sure this is not a duplicate issue
- [x] This issue does not contain any sensitive information 

**Platform**

In-game, both Java and Bedrock

**Describe the feature**

If a user sends a message that contains the words "join" or "minehut gg" and an existing server's name next to these words their message should be deleted automatically (not by a mod because mods can't be on the server 24/7) and they should get a message telling them to use /ad or /advertise

The message shouldn't be deleted if the player is using /msg (and similar commands if there are more) so that players can tell their friends to join their server, I highly doubt a spammer would send a private message to the whole lobby just to bypass this

*How the feature is useful**

This feature would benefit everyone because the chat wouldn't be filled with people advertising their servers when the mods aren't on but people would still be able to help others if someone asks how to join a server. For example, they could say something like "say /join and the server's name" or just "with /join"

I've been thinking of the best way of doing this for a long time and this is the best idea I could think of, with this feature it wouldn't be neccesary to mute spammers or to tell them to use /ad (unless they try to bypass it but I don't see why someone would prefer to bypass this instead of just using /ad)

---
**Use 👍 and 👎 reactions to indicate you agree or disagree with this suggestion! Feel free to discuss the idea in the comments.**

**Comment by PundaChen** [comment] 2021-02-05 11:37
Gone over this in the past, this won't be done because we wouldn't be able to tell a user how to join their server (and trust me, we get that question more than you'd think)

**Comment by MGSuco** [comment] 2021-02-05 11:55
> Gone over this in the past, this won't be done because we wouldn't be able to tell a user how to join their server (and trust me, we get that question more than you'd think)

We would if we don't say a server's name, I gave an example under "How the feature is useful"
but I'm not sure if it's possible to check if the message contains a server's name so it might still not be worth trying

**Comment by MrTibo1** [comment] 2021-02-05 11:57
message contains /join or join or anything in that way that could be used in an advertising message -> message contains a server name -> block

**Comment by MGSuco** [comment] 2021-02-05 12:17
That's not what I meant by "server name"
I mean that it would check if the message contains a word that's in a list of Minehut servers or something and then block the message if it does
But I'm not sure if that's be possible

**Comment by MrTibo1** [comment] 2021-02-05 12:18
> > message contains /join or join or anything in that way that could be used in an advertising message -> message contains a server name -> block
> 
> That's not what I meant by "server name"
> I mean that it would check if the message contains a word that's in a list of Minehut servers or something and then block the message if it does
> But I'm not sure if that's be possible

> "a server name"

**Comment by MGSuco** [comment] 2021-02-05 12:49
> > > message contains /join or join or anything in that way that could be used in an advertising message -> message contains a server name -> block
> > 
> > 
> > That's not what I meant by "server name"
> > I mean that it would check if the message contains a word that's in a list of Minehut servers or something and then block the message if it does
> > But I'm not sure if that's be possible
> 
> **"_a server name_"**

I mean the word that's before ".minehut.gg" in your server's ip

for example if someone says "use /join" it wouldn't be deleted because there are no servers called "use" but if someone says "join my server [server name]" it would get deleted because they said "join" and a server's name in the same message

but if someone says something like "I don't join dupe servers" it would get deleted too because there is a server called "dupe"

**Comment by MrTibo1** [comment] 2021-02-05 14:24
> I mean the word that's before ".minehut.gg" in your server's ip
I... I know that is what you mean, that's why i wrote _**-->> A <<-- server name**_

**Comment by MGSuco** [comment] 2021-02-05 15:02
> > I mean the word that's before ".minehut.gg" in your server's ip
> 
> I... I know that is what you mean, that's why i wrote _**-->> A <<-- server name**_

Sorry, I still don't get what you're saying lol

**Comment by MrTibo1** [comment] 2021-02-05 15:48
> Sorry, I still don't get what you're saying lol

I'm saying "a server name" how do you not understand that. It means exactly what you mean, the name of a server, the part that goes before .minehut.gg, the string you use to /join <a server name>. **_a. server. name._**

**Comment by LukasmanMHdude** [comment] 2021-02-05 16:15
#474

**Comment by LukasmanMHdude** [comment] 2021-02-05 16:16
dupe of #374

**Closed** 2021-02-05 16:17 UTC
Labels: feature request

**Comment by MGSuco** [comment] 2021-02-05 16:33
> > Sorry, I still don't get what you're saying lol
> 
> I'm saying "a server name" how do you not understand that. It means exactly what you mean, the name of a server, the part that goes before .minehut.gg, the string you use to /join . **_a. server. name._** smh

ohhh ok, the "->" confused me because it looked like if meant "so" or "then" but it actually meant "and"
and your second and third messages confused me even more lol

**Comment by MGSuco** [comment] 2021-02-05 16:34
> dupe of #374

Oh sorry didn't see that one
Thanks for telling

**Comment by LukasmanMHdude** [comment] 2021-02-05 16:54
@MGSuco are you on the discord btw?

**Comment by MGSuco** [comment] 2021-02-05 17:55
> @MGSuco are you on the discord btw?

You mean Minehut's discord? I was some hours ago but left because I joined just to ask how to make a suggestion and here we are now lol
how do you mark a comment as off-topic?

**Comment by LukasmanMHdude** [comment] 2021-02-05 18:01
> > @MGSuco are you on the discord btw?
> 
> You mean Minehut's discord? I was some hours ago but left because I joined just to ask how to make a suggestion and here we are now lol
> how do you mark a comment as off-topic?

this is the minehut meta discord: https://discord.com/invite/pgXMSFh we talk about stuff that's suggestion online sometimes
